### ISSUE TITLE
Error 'login' Authme 5.2

### ISSUE THREAD

**Issue by DardBrinza** [Xephi/AuthMeReloaded#376] opened 2015-12-24 14:30 UTC
I use spigot latest spigot 1.8.8 and authme 5.2 #582
Error:
http://pastebin.com/CRUTpTGc

**Comment by ljacqu** [comment] 2015-12-24 14:34
Do you have any idea what the player invoked? From the error it seems to me that he wrote `/login` (just that) but I can't reproduce it.

**Comment by ljacqu** [comment] 2015-12-24 14:47
Thanks for the report; it should be fixed as of build nr. 585.
http://ci.xephi.fr/job/AuthMeReloaded-Dev/

**Comment by DardBrinza** [comment] 2015-12-24 19:31
Fixed. Thanks :) Close.

**Closed** 2015-12-24 21:06 UTC
Labels: bug, please-verify
