### ISSUE TITLE
Disable kickforvip

### ISSUE THREAD

**Issue by YellowZaki** [Xephi/AuthMeReloaded#1001] opened 2016-11-11 10:05 UTC
Some players are being randomly kicked with the message: A VIP player has joined the server when it was full!
I have added to the default group the permission authme.vip and it keeps happening. What can I do?
Thanks

**Comment by ljacqu** [comment] 2016-11-12 18:39
Players with the permission node `authme.vip` may join a full server and someone without this permission will be kicked. If you want this feature disabled, do not assign the `authme.vip` permission to anyone. The default nodes `authme.player.*` and `authme.admin.*` don't include `authme.vip` so in case you use those, that's no issue.

Opped users get this permission by default, if it happens for other users we need to investigate this further. Please keep us updated.

Permissions: https://github.com/AuthMe/AuthMeReloaded/blob/master/docs/permission_nodes.md

**Comment by YellowZaki** [comment] 2016-11-14 10:22
Anybody has the permission authme.vip, just OPs (by default). That's why I added authme.vip to all users.

**Comment by ljacqu** [comment] 2016-11-14 22:23
My suggestion was to remove the authme.vip permission from everyone (including ops) since what you actually want is NOT for anyone to have this feature. Assigning the permission node to everyone should behave the same way, but semantically it's less clear.

Anyway, even with your setup no one should be kicked. To make sure that this comes from AuthMe and not from some other plugin, could I ask you to change the translation to something else and to make sure that the user will get this message? (This confirms that AuthMe is the source of the kick.)

In the meantime, I'll assign this issue to me and I'll see if I can reproduce it tomorrow.

**Comment by YellowZaki** [comment] 2016-11-14 22:28
Yes, I'm sure the message comes from authme.
PD: my server player limit is 12 but the group member has the permission essentials.joinfullserver so there is no limit. (I can't change the 12 because of my server hosting)

**Comment by ljacqu** [comment] 2016-11-19 10:31
Sorry for the late answer. In your config.yml, please set the following two things to enable logging to authme.log:

```yml
    # Log level: INFO, FINE, DEBUG. Use INFO for general messages,
    # FINE for some additional detailed ones (like password failed),
    # and DEBUG for debugging
    logLevel: 'DEBUG'
  ...
        # Copy AuthMe log output in a separate file as well?
        logConsole: true
```

Then please use the JAR given in https://github.com/ljacqu/AuthMeReloaded/tree/1001-vip-status-debug/samples (spigot or legacy, whichever you use). It will write a debug line each time a player joins. It would be interesting to see what comes out when the server is full and players join.

**Comment by YellowZaki** [comment] 2016-11-19 19:00
Here is a piece of the log (the full log have 207 messages Server is full and player is NOT VIP):
`[11-19 12:22:24]: [FINE] The user LUIS920 has 3 accounts:
[11-19 12:22:24]: [FINE] §7luis123xd, luis75308, §aLUIS920§7.
[11-19 12:22:24]: [FINE] LUIS920 logged in!
[11-19 12:22:40]: [DEBUG] Server is full and player is NOT VIP: refusing neko_nyagamer
[11-19 12:23:26]: [DEBUG] Server is not full: allowing leonardus
[11-19 12:23:34]: [DEBUG] Server is not full: allowing luis38
[11-19 12:23:36]: [FINE] leonardus logged in!
[11-19 12:23:40]: [DEBUG] Server is not full: allowing Yuutaotaku
[11-19 12:23:40]: [FINE] The user Yuutaotaku has 2 accounts:
[11-19 12:23:40]: [FINE] §7yuutaotaku7w7, §aYuutaotaku§7.
[11-19 12:23:40]: [FINE] Yuutaotaku logged in!
[11-19 12:23:47]: [FINE] The user luis38 has 2 accounts:
[11-19 12:23:47]: [FINE] §7§aluis38§7, dayi.
[11-19 12:23:47]: [FINE] luis38 logged in!
[11-19 12:24:25]: [DEBUG] Server is not full: allowing DFilexD
[11-19 12:24:31]: [FINE] DFilexD logged in!
[11-19 12:24:33]: [DEBUG] Server is not full: allowing leonardus
[11-19 12:24:33]: [FINE] leonardus logged in!
[11-19 12:24:55]: [DEBUG] Server is not full: allowing RubenFlox
[11-19 12:25:00]: [FINE] RubenFlox logged in!
[11-19 12:25:12]: [DEBUG] Server is not full: allowing darklionel
[11-19 12:25:12]: [FINE] darklionel logged in!
[11-19 12:25:12]: [FINE] darklionel logged in!
[11-19 12:25:32]: [DEBUG] Server is not full: allowing SkootHacker
[11-19 12:25:34]: [DEBUG] Server is not full: allowing Neko_NyaGamer`

**Comment by ljacqu** [comment] 2016-11-20 10:49
> [11-19 12:22:40]: [DEBUG] Server is full and player is NOT VIP: refusing neko_nyagamer

If neko_nyagamaer was able to log in at that point (you can look that up in the main server log), then it's something else that is allowing players to join, e.g. Essentials has a permission that allows players to join on full server.

If there is no line in the authme.log that says something like "Player xxx is VIP; kicking non-VIP player yyy" then what you're experiencing is not AuthMe's fault.

**Comment by ljacqu** [comment] 2016-11-24 10:21
@YellowZaki If there is no line in the authme.log that says something like "Player xxx is VIP; kicking non-VIP player yyy" then authme is never kicking players because of vip

**Closed** 2016-12-03 10:41 UTC
Labels: no answer, question
