### ISSUE TITLE
[Request] Register with password and email at the same time.

### ISSUE THREAD

**Issue by koca2000** [Xephi/AuthMeReloaded#1029] opened 2016-12-10 16:36 UTC
Is it possible to edit registration command to "/register <password> <password again> <email>"? I can't see even any function to set player email in api.

**Comment by ljacqu** [comment] 2016-12-10 21:10
Duplicate of #427

**Closed** 2016-12-11 01:03 UTC
Labels: duplicate

**Comment by koca2000** [comment] 2016-12-13 18:43
Can I force players to use "/register <password> <email>" as only possible command?

**Comment by sgdc3** [comment] 2016-12-13 19:12
in our config:

        # Allowed commands for unauthenticated players
        allowCommands: 
        - '/login'
        - '/register'
        - '/l'
        - '/reg'
        - '/email'
        - '/captcha'

**Comment by koca2000** [comment] 2016-12-13 19:14
Sorry Github have changed my message. I wrote "/register (password) (email)".

**Comment by sgdc3** [comment] 2016-12-13 19:15
not atm, we need to implement that

**Comment by koca2000** [comment] 2016-12-13 19:16
Would you implement it before christmas?

**Comment by sgdc3** [comment] 2016-12-13 19:17
I have no time for it, maybe @ljacqu @Gnat008 or @Xephi ? ;)

**Comment by ljacqu** [comment] 2016-12-13 20:54
Yeah maybe on Friday or Saturday, I'll assign the other issue to me ;) If someone else wants to do it you can just unassign me
