### ISSUE TITLE
using php's password hashing api

### ISSUE THREAD

**Issue by sachaw** [Xephi/AuthMeReloaded#533] opened 2016-02-16 01:43 UTC
I am using php7 and the password hashing api, for example a register function could be:
`$options = [
        'salt' => uniqid(mt_rand(), true),
        'cost' => 12
    ];
    $hash = password_hash($_POST["password"], PASSWORD_DEFAULT, $options);`
which creates a hash like: `$2y$12$199083790356be8bda908Om6AZXfMNcwbq6uYQfPEdXIYwP3jvSjy`
this is using BCrypy BTW.
so when I go to my authme config and change password hash: BCRYPT, it doesn't work. any ideas?

**Comment by sachaw** [comment] 2016-02-18 22:37
Hoping to get a reply soon, thanks.

**Comment by sgdc3** [comment] 2016-02-18 22:59
@DNx5 Bump, maybe our bcrypt algorithm is different ;)

**Comment by DNx5** [comment] 2016-02-18 23:02
our bcrypt algorithm doesn't have separated salt.
@sachaw could you try to set
`bCryptLog2Round: 12` in your config.yml ?

**Comment by sachaw** [comment] 2016-02-18 23:49
no, ill try thanks.

**Comment by sachaw** [comment] 2016-02-19 03:36
No luck, I changed `bCryptLog2Round: 10` to `12` no luck, i verified my hash in php was correct with `password_get_info($hash)` which returned `array(3) { ["algo"]=> int(1) ["algoName"]=> string(6) "bcrypt" ["options"]=> array(1) { ["cost"]=> int(12) } }` so nothing seems odd, I have no clue what else to try, any ideas?

**Comment by DNx5** [comment] 2016-02-19 04:44
could you change your options variable to this,
`$options = [ 'cost' => 12 ];` cost depends on your bCryptLog2Round value in config.yml
note: it may break your old hash if you have one.

**Comment by sgdc3** [comment] 2016-02-19 16:04
@sachaw

**Comment by games647** [comment] 2016-02-19 16:17
@sachaw 
Infact the Bcrypt implementation is different. The library we use uses $2a. Could you try to set "BCRYPT2Y" as encryption method in your authme config.

**Comment by DNx5** [comment] 2016-02-19 16:35
:laughing: ah I didn't notice that. but still, it doesn't have separated salt.

**Comment by games647** [comment] 2016-02-19 16:41
>:laughing: ah I didn't notice that. but still, it doesn't have separated salt.

Neither does PHP.

**Comment by ljacqu** [comment] 2016-02-19 17:55
Assigning to me as I will provide a fully functional sample

**Comment by ljacqu** [comment] 2016-02-19 18:16
@sachaw
https://github.com/AuthMe-Team/AuthMeReloaded/tree/master/samples/website_integration/bcrypt
Using the two files there ^ I can log in and register both ways (on the php page and in AuthMe). But new registration may not work in AuthMe due to database cache. If you restart the plugin then it works. But that's another issue.

**Comment by sachaw** [comment] 2016-02-20 05:10
thanks, trying it now

**Comment by sachaw** [comment] 2016-02-20 05:36
half working:
If i register with AuthMe I can login to my server and online - Good.
If i register with  with my registration script, I can login to my site but not my server - Bad.
my `config.yml` has the following confg:
`passwordHash: BCRYPT`
`bCryptLog2Round: 12`
My registration function I have tried:
`$options = [ 'cost' => 12 ];
$hash = password_hash($_POST["password"], PASSWORD_BCRYPT, $options);`
and
`$hash = password_hash($_POST["password"], PASSWORD_BCRYPT);`
but to no success, any ideas?

**Comment by ljacqu** [comment] 2016-02-20 06:01
Does it work with the files I linked to? If so, kindly post your entire php code (or create a repo and I'll send a PR tofix it). 
If not, we need to troubleshoot

**Comment by ljacqu** [comment] 2016-02-20 06:02
Oh, this might be because:

> But new registration [from the php page] may not work in AuthMe due to database cache. If you restart the plugin then it works. But that's another issue.

Could you please check if that is the issue?

**Comment by sachaw** [comment] 2016-02-20 06:05
ill try thanks.

**Comment by sachaw** [comment] 2016-02-20 06:12
db cache is not the problem, must be my register function, here's a simplistic version, please the procedural style, just used to try 2 get 2 work.
`session_start();
if ($_POST["password"] != $_POST["verify"]) {
    header('Location: ../../login/invite/new?error=mismatch');
} else {
    include '../mysql.php';
    $options = [
        'cost' => 12
    ];
     $hash = password_hash($_POST["password"], PASSWORD_BCRYPT);
    $query = "INSERT INTO `users` (`password`, `user_level`, `username`, `first_name`, `last_name`, `avatar_ext`, `aboutme`) VALUES ('". $hash ."', '0', '". $_POST["username"] ."', '". $_POST["first_name"] ."', '". $_POST["last_name"] ."', 'default.png', '');";
    $result = mysqli_query($conn, $query);
    $query = "DELETE FROM `invites`WHERE `code` = '". $_SESSION["invite_code"] ."'";
    $result = mysqli_query($conn, $query);
    session_destroy();
    session_start();
    $_SESSION["account"]["username"] = $_POST["username"];
    $_SESSION["account"]["ip"] = $_SERVER["REMOTE_ADDR"];
    header('Location: ../../account');
}
`

**Comment by ljacqu** [comment] 2016-02-20 06:15
Does it work with the files I linked to?

**Comment by sachaw** [comment] 2016-02-20 06:20
was getting some errors `
Fatal error: Call to a member function bind_param()`

**Comment by sachaw** [comment] 2016-02-20 06:20
and similar error on login

**Comment by ljacqu** [comment] 2016-02-20 06:43
OK, i had to remove some stuff from your script since I don't have an "invites" table etc.
```php
<?php
error_reporting(E_ALL);
if (isset($_POST['password'])) {
	$conn = mysqli_connect('localhost', 'root', '', 'authme');
     $hash = password_hash($_POST["password"], PASSWORD_BCRYPT);
    $query = "INSERT INTO `authme` (`password`, `username`) VALUES ('". $hash ."', '" . $_POST["username"] . "');";
    $result = mysqli_query($conn, $query);
	var_dump('success of query:', $conn, $result);
}

?>
<form method="post">
 username <input type="text" name="username" />
 <br /> password <input type="text" name="password" />
 <br /><input type="submit" />
</form>
```

Sent a request, verified that it was put into authme, started the server, could log in just fine. I would suggest outputting the queries you execute, try them manually, make sure that they go through. Make sure that `$result` is `true` after executing; things like this.
If caching is not a problem I think the cause is somewhere other than the password hash.

**Comment by sachaw** [comment] 2016-02-20 06:58
I think it is a problem with verifying the password on the plugin side, can you please supply you config.yml please, as the hash inserted into my db from your script works for logging into my site but not the server.

**Comment by sachaw** [comment] 2016-02-20 06:58
I am certain the hash is fine

**Comment by ljacqu** [comment] 2016-02-20 07:06
I have 
```
        passwordHash: 'BCRYPT'
```

I left `bCryptLog2Round: 10`, that shouldn't be an issue. My entire config is here: http://pastebin.com/rf5AhPgQ but I wouldn't suggest to use it. I use this for development so I switch around different settings and I'm not exactly sure what is enabled/disabled at this point since it's not for an external server.

**Comment by sachaw** [comment] 2016-02-20 07:19
heres what i tried:
1| register with the server, can login to server and mc.
use `var_dump(password_get_info("$2a$10$.xzsPPVHX09Hx9qGv0T0OufjVCsENg2lP.9IMQkgoirzzoM2IlRY."));` on site, but returns:
`array(3) { ["algo"]=> int(0) ["algoName"]=> string(7) "unknown" ["options"]=> array(0) { } }`
I have no clue, it just keeps getting more and more confusing.

**Comment by sachaw** [comment] 2016-02-20 07:34
ignore the last part of my pervious comment, I tried a few bcrypt generators online, all of which let me login to my site with and the server, so there must be something when im gernerating a hash

**Comment by sachaw** [comment] 2016-02-20 07:40
think there's something wrong with my salt, as a hash generated by the plugin works by verifying with https://www.dailycred.com/article/bcrypt-calculator but one that php generates does not. I dont want a custom salt, as 

> The salt option has been deprecated as of PHP 7.0.0. It is now preferred to simply use the salt that is generated by default.

**Comment by sachaw** [comment] 2016-02-20 08:03
after trying my options, I just need to know if i can get AuthMeReloaded to use `$2y`, I can't do this in the config with `BCRYPT2Y`

**Comment by sachaw** [comment] 2016-02-20 08:06
Just looked ad https://github.com/Xephi/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/security/HashAlgorithm.java and noticed that `BCRYPT2Y` was ther but in my log `[WARN] [AuthMe] ERROR: Unknown Hash Algorithm; defaulting to SHA256`

**Comment by sachaw** [comment] 2016-02-20 08:52
just scanned the jar that i have 5.0beta3(dont know if it's upto date but couldnt find a newer one anywhere else) which contained no information on BCRYPT2Y, so if anyone has a more recent compiled version, could you please supply me with one thanks.

**Comment by sachaw** [comment] 2016-02-20 08:57
NM, Finally git it working. Thanks for your help, especially @ljacqu

**Closed** 2016-02-20 11:47 UTC
Labels: question
