### ISSUE TITLE
[Dev] Reload = lost database connection

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#575] opened 2016-03-01 21:29 UTC
Can't provide more infos ATM

**Comment by sgdc3** [comment] 2016-03-01 21:42
https://github.com/elBukkit/MagicPlugin/issues/45#issuecomment-190916656 << Original discussion

**Comment by Blamo27** [comment] 2016-03-01 22:17
@sgdc3 Maybe you should check, If the connection to SQL before the authme reload is closed ?

**Comment by sgdc3** [comment] 2016-03-01 22:58
Yeah, already checked ;) The cause is elsewhere...

**Comment by sgdc3** [comment] 2016-03-01 23:42
this is an evolution of #552

**Comment by sgdc3** [comment] 2016-03-01 23:43
Whoops damn mobile client xD

**Comment by Platinteufel** [comment] 2016-03-04 02:53
Also happens with SQLITE

**Comment by Platinteufel** [comment] 2016-03-05 11:34
Does it only happen with Spigot 1.9? 
I don't remember getting this error before, so it must be because Spigot 1.9 or a patch from the latest dev-builds.

**Comment by sgdc3** [comment] 2016-03-05 11:36
In 1.9 Mysql doesn't work, it seems to be an issue with our connection pool library (HikariCP).
Other projects that use this dependency (LogBlock, ..) is having the same issue...

**Comment by Platinteufel** [comment] 2016-03-05 11:46
Maybe create a spigot issue?
https://hub.spigotmc.org/jira/secure/Dashboard.jspa

**Comment by sgdc3** [comment] 2016-03-05 12:27
https://github.com/LogBlock/LogBlock/issues/660#issuecomment-192625165

**Comment by Platinteufel** [comment] 2016-03-05 12:37
Hm, I've tested LogBlock with MySQL and Spigot 1.9 yesterday and it worked very well. Does this error also happen only after reloading the plugin?

**Comment by ljacqu** [comment] 2016-03-05 12:51
http://stackoverflow.com/questions/22201536/jdbc-mysql-connection-works-on-some-tomcats-but-fails-on-others-with-mysqlnontra

**Comment by sgdc3** [comment] 2016-03-05 12:52
Damn...

**Comment by sgdc3** [comment] 2016-03-05 12:53
Thanks @ljacqu, now i'm trying to update hikari to latest snapshot and check if they found a workaround...

**Comment by Platinteufel** [comment] 2016-03-05 13:09
Would be awesome if this could be solved without needing a new startup flag ^^

**Comment by sgdc3** [comment] 2016-03-05 13:13
@Platinteufel I updated Hikari, can you try latest build without the flag?

**Comment by Platinteufel** [comment] 2016-03-05 13:21
Sure, I'm not at home atm, but I will test it in 2-3 hours.

**Comment by sgdc3** [comment] 2016-03-05 13:25
@Platinteufel Thank you ;)

**Comment by Platinteufel** [comment] 2016-03-05 16:13
@sgdc3 Just tested it with SQLITE -> Error http://pastebin.com/dxbW5WzK

I will test it with MySQL soon.

**Comment by Platinteufel** [comment] 2016-03-05 16:18
I'd suggest dropping /authme reload support till this is fixed, it's quite critical ..

**Comment by sgdc3** [comment] 2016-03-05 16:36
Ok, the flag is required...

**Comment by Platinteufel** [comment] 2016-03-05 16:44
:(

**Comment by Platinteufel** [comment] 2016-03-05 16:44
But why it wasn't required in 1.8?

**Comment by sgdc3** [comment] 2016-03-05 16:50
@Platinteufel Because the built-in sql library have been updated with CraftBukkit 1.9

**Comment by Platinteufel** [comment] 2016-03-05 16:53
Do you think it helps if I create a spigot ticket for md_5 and his team?

**Comment by sgdc3** [comment] 2016-03-05 16:54
Maybe later, this is not Spigot's fault, it's an issue with the library. The only thing that Spigot team can do is downgrade it.

**Comment by sgdc3** [comment] 2016-03-05 16:55
@Platinteufel Can you test now SQLITE with the flag?

**Comment by Platinteufel** [comment] 2016-03-05 16:56
Yeah sure, just a moment

**Comment by Platinteufel** [comment] 2016-03-05 17:01
Same error with this startup script: :confused: 

@echo off

java -Xmx1024M -Xms256M -Dfile.encoding=UTF-8 -jar craftbukkit.jar
pause

**Comment by sgdc3** [comment] 2016-03-05 17:02
:/

**Comment by sgdc3** [comment] 2016-03-05 17:03
@Platinteufel Ok now we need to check with mysql.

**Comment by sgdc3** [comment] 2016-03-05 17:03
Maybe it's just sqlite (I hope)

**Comment by Platinteufel** [comment] 2016-03-05 17:13
[18:13:09 WARN]: [AuthMe] Error during SQL operation: [SQLException]: HikariDataSource HikariDataSource (AuthMeMYSQLPool) has been closed. :pensive:

**Comment by Platinteufel** [comment] 2016-03-05 17:14
Could you drop _/authme reload_ support till there's a solution for it?

**Comment by sgdc3** [comment] 2016-03-05 17:14
...

**Comment by sgdc3** [comment] 2016-03-05 17:15
@Platinteufel Wait, if you ignore the reload command everything is fine, right?

**Comment by Platinteufel** [comment] 2016-03-05 17:15
Yeah sure

**Comment by Platinteufel** [comment] 2016-03-05 17:16
But if someone uses /authme reload ...

**Comment by sgdc3** [comment] 2016-03-05 17:17
So you can run authme on CB 1.9 without the flag?

**Comment by sgdc3** [comment] 2016-03-05 17:18
Both Mysql and Sqlite?

**Comment by Platinteufel** [comment] 2016-03-05 17:18
Yeah fine, both. The only problem is if some of my Admins uses this command - thereforce I asked for dropping the support.

**Comment by sgdc3** [comment] 2016-03-05 17:19
Note that there is an option to disable it: hooks: reloadSupport if i'm not wrong :/

**Comment by Platinteufel** [comment] 2016-03-05 17:21
Oh lol .. okay, I'm blind, sorry.

**Comment by Platinteufel** [comment] 2016-03-05 17:25
WAIT lol: On my main server I'm running build 683. Just tested it with CB 1.9 .. no database problems!

**Comment by sgdc3** [comment] 2016-03-05 17:31
Can you try on a sandbox server with latest build? http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by Platinteufel** [comment] 2016-03-05 17:33
Well I've tested on a sandbox server CB 1.9 with 866 -> Error after /authme reload
Then I've tested with 683 (from my main server) -> No database errors

**Comment by Platinteufel** [comment] 2016-03-05 17:36
I'm sorry but you the issue was patched into AuthMe in some build between 683 and the latest ...

**Comment by Platinteufel** [comment] 2016-03-05 17:44
I'm not sure what you've changed since 683, but I'm sure there were some database patches like
https://github.com/AuthMe-Team/AuthMeReloaded/commit/7c1dd888cc2a660adf3ba7dea2f05aa0ab24aca9#diff-965206ed6ff261a1445c070a75061ad8
that aren't supported by /authme reload. And I think that's the problem.

**Comment by Platinteufel** [comment] 2016-03-05 17:56
... I've tested it with build 864 -> no problems. I can say you what had broken this in a few minutes ..

**Comment by Platinteufel** [comment] 2016-03-05 17:59
Error occurs since build 856 http://ci.xephi.fr/job/AuthMeReloaded/856/
**All builds before don't have any database errors in CB 1.9**

**Comment by sgdc3** [comment] 2016-03-05 18:18
@ljacqu Any ideas? I checked your code but i didn't find anything suspicious :/

**Comment by Platinteufel** [comment] 2016-03-05 18:59
Hm ..

Caused by: java.lang.NullPointerException
at org.sqlite.PrepStmt.<init>(PrepStmt.java:42)
at org.sqlite.Conn.prepareStatement(Conn.java:404)
at org.sqlite.Conn.prepareStatement(Conn.java:399)
at org.sqlite.Conn.prepareStatement(Conn.java:383)
at fr.xephi.authme.datasource.SQLite.updateSession(SQLite.java:264)
at fr.xephi.authme.datasource.CacheDataSource.updateSession(CacheDataSource.java:118)
at fr.xephi.authme.process.quit.AsynchronousQuit.process(AsynchronousQuit.java:53)
**at fr.xephi.authme.process.Management$5.run(Management.java:95)**

Management has been changed in this patch

**Comment by ljacqu** [comment] 2016-03-05 20:26
Checking it, thanks for the mention @sgdc3 and for the detailed analysis @Platinteufel. I will comment back shortly

**Comment by ljacqu** [comment] 2016-03-05 20:29
Of course, in commit https://github.com/AuthMe-Team/AuthMeReloaded/commit/d664e7be26bc945931a2160d0e5380eeca7f0bc7 I pass the data source to Management as a parameter instead of getting it through AuthMe.getDatabase() or whatever the method is.

I still want to keep it like this but the fix should be to recreate Management when we reload, which is what I intended to do once more things were cleaned up. Of course I didn't think about the problems during the intermediate state.... ouch :P

**Comment by Platinteufel** [comment] 2016-03-05 21:18
No problem. :) Is it possible to provide a fix today, or will this take a few days? I actually want to update my server to CB 1.9 tonight, but I don't want to install a broken AuthMe-Snapshot.

**Comment by ljacqu** [comment] 2016-03-05 21:19
This has the highest priority for me atm and I expect to have a fix within this hour :)

**Comment by ljacqu** [comment] 2016-03-05 21:33
@Platinteufel this should now be fixed within build nr. 870 or higher ([Jenkins](http://ci.xephi.fr/job/AuthMeReloaded/870/)). It's not a nice fix and so my next priority will be to fix this asap. Sorry for all the trouble. :/

**Comment by Platinteufel** [comment] 2016-03-05 21:41
Works fine in 870, thank you for the fast fix @ljacqu :)

**Comment by ljacqu** [comment] 2016-03-05 21:47
Thanks a lot for the feedback, and as mentioned before for the detailed analysis. That was very helpful :)

**Closed by ljacqu** 2016-03-05 21:47 UTC
Labels: bug, critical, please verify
