### ISSUE TITLE
Inventory wipes are back

### ISSUE THREAD

**Issue by MithrandirCraft** [Xephi/AuthMeReloaded#438] opened 2016-01-13 16:15 UTC
It seems that this horrible bug is somehow reemerging on my server. I wouldn't dare confirm this is 100% Authme's fault, as the inventory protection system has been improved, but sometimes during restarts/logouts, there are occasional inventory losses.
But I do recall this issue being caused by Authme some time before during logouts/restarts.

I've already got a few reports in on this :/

If I can get any more information I will provide it.

---------------------------------
Spigot version: 1.8.8
Authme version: 5.2-SNAPSHOT-b682

**Comment by games647** [comment] 2016-01-13 16:22
Do you have ProtocolLib installed?

**Comment by MithrandirCraft** [comment] 2016-01-13 16:22
@games647 Yes.

**Comment by Platinteufel** [comment] 2016-01-16 05:25
Do you have any more information about inventory problems with AuthMe? I want to update my server to the latest 5.2-devbuild tomorrow, so I need to know if it's safe to update or if I'll messing up my players inventories.

**Comment by MithrandirCraft** [comment] 2016-01-17 14:05
@Platinteufel I would say it's rather rare for players to get inventory wipes.

The problem is, not everyone reports this on my server. I only got 2 reports untill now.

It may not even be Authme's fault. It's definetly a rare bug.

**Comment by Platinteufel** [comment] 2016-01-17 15:02
I'm running the latest snapshot + MultiInv b70 since two days and can't confirm any inventory wipes yet.

**Comment by sgdc3** [comment] 2016-01-17 23:15
@MithrandirCraft Can you check this? #447

**Comment by games647** [comment] 2016-01-18 17:17
@sgdc3 This is the new SNAPSHOT version. It shouldn't be related to #477.

**Comment by Platinteufel** [comment] 2016-01-18 17:41
#447 is an issue with an old AuthMe version. Anyways, I'm still not able to reproduce any inventory wipes in the latest 5.2-snapshots. I would say it isn't AuthMes fault.

**Comment by sgdc3** [comment] 2016-05-05 17:04
@MithrandirCraft Closing, please tell me if this issue is still happening.

**Closed by sgdc3** 2016-05-05 17:04 UTC
Labels: bug
