### ISSUE TITLE
/REG and /ChangePassword bug??

### ISSUE THREAD

**Issue by WaterXCubic** [Xephi/AuthMeReloaded#94] opened 2015-07-05 10:41 UTC
I am using the lastest dev version and thats #17,i am just using a testing server,when the plugin tolds me to register,i used /reg WaterXCubic WaterXCubic and thats my username,i used tab to get it,it says they are not the same,i manully type it myself,and it also said that

However,i used /reg 123456 123456 and it worked fine

**Comment by WaterXCubic** [comment] 2015-07-05 10:41
#17 is not the issue #17,its only dev number #17

**Comment by Xephi** [comment] 2015-07-05 10:43
Haven't understand the problem x) what's your username, what password do you try and what the result of it?

**Comment by sgdc3** [comment] 2015-07-05 10:43
It's because it's your name, we haven't a language string for this situation.

**Comment by WaterXCubic** [comment] 2015-07-05 10:45
My username is WaterXCubic,and i am using WaterXCubic for the password and it says those password and repeat password are not same when i am registering

**Comment by WaterXCubic** [comment] 2015-07-05 10:45
@sgdc3 It worked fine for previous stable version like 3.4 i think

**Comment by sgdc3** [comment] 2015-07-05 10:45
I think the problem is: When I use my nickname as password it prints the "not the same" message

**Comment by WaterXCubic** [comment] 2015-07-05 10:46
Yep

**Comment by sgdc3** [comment] 2015-07-05 10:46
It should print: "You can't use your nickname as password!

**Comment by WaterXCubic** [comment] 2015-07-05 10:46
I am using ZHHK idk does it matter :P

**Comment by sgdc3** [comment] 2015-07-05 10:46
@Xephi Right?

**Comment by sgdc3** [comment] 2015-07-05 10:47
Also english and italian translation haven't an adequate string, but I remember this function was implemented, right?

**Comment by sgdc3** [comment] 2015-07-05 10:54
:package: 
'''
        else if ((lowpass.equalsIgnoreCase(player.getName()) || lowpass.contains("delete") || lowpass.contains("where") || lowpass.contains("insert") || lowpass.contains("modify") || lowpass.contains("from") || lowpass.contains("select") || lowpass.contains(";") || lowpass.contains("null")) || !lowpass.matches(Settings.getPassRegex)) {
            m.send(player, "password_error");
            allowRegister = false;
        }
'''
From AsyncronousRegister.java

**Comment by WaterXCubic** [comment] 2015-07-05 10:56
idk how to script,but actually,i can observer that is telling me that if the password contains player's name,it will not allow register

**Comment by sgdc3** [comment] 2015-07-05 10:58
IF PASSWORD lowpass.equalsIgnoreCase(player.getName()) SEND MESSAGE password_error

We should create a new message named password_error_nick

**Comment by sgdc3** [comment] 2015-07-05 10:58
@Xephi

**Comment by sgdc3** [comment] 2015-07-05 11:00
It also appends with unsafepasswords:

```java
        if (!Settings.unsafePasswords.isEmpty()) {
            if (Settings.unsafePasswords.contains(password.toLowerCase())) {
                m.send(player, "password_error");
                return;
            }
        }
```

**Comment by sgdc3** [comment] 2015-07-05 11:01
Also in ChangePasswordCommand.java

**Comment by sgdc3** [comment] 2015-07-05 13:18
Fixed in my PR

**Comment by Maxetto** [comment] 2015-07-05 18:38
I asked for this feature (too many people is using unsafe password/their username). However, I told Xephi that we need a proper message for this error.

**Comment by sgdc3** [comment] 2015-07-05 18:53
it also needs an enable/disable option in the configuration

**Comment by Maxetto** [comment] 2015-07-05 18:57
Meh... For safety, I would let this always active. Disabling that means almost halving the protection (I know it's like impossible, but so many people use their Username as Password. Mostly in Minecraft!)

**Comment by sgdc3** [comment] 2015-07-05 19:16
@Maxetto Yes, you're right ;)

**Comment by WaterXCubic** [comment] 2015-07-06 07:08
But for my convinient i would just use my name lol,so the option is still needed ;D

**Comment by sgdc3** [comment] 2015-07-06 10:41
@WaterXCubic This is also true ;) @Xephi

**Closed** 2015-07-30 00:51 UTC
