### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by xyblues** [Xephi/AuthMeReloaded#548] opened 2016-02-21 09:31 UTC
[1.txt](https://github.com/Xephi/AuthMeReloaded/files/139536/1.txt)

**Comment by ljacqu** [comment] 2016-02-21 10:06
@xyblues Thanks for the log! 
How many other plugins do you have and how long (with how many players) does it take for this to happen? I'm trying to get a feeling of the dimensions.

--- 

@ Devs, analyzing the log

```
[12:23:14] [Spigot Watchdog Thread/ERROR]: 	Thread is waiting on monitor(s):
[12:23:14] [Spigot Watchdog Thread/ERROR]: 		Locked on:fr.xephi.authme.datasource.CacheDataSource.getAuth(CacheDataSource.java:69)
```
Might something be causing blocking in CacheDataSource? Most of the threads with `State: BLOCKED` have a stacktrace pointing to CacheDataSource!

-
Other (but probably somewhat minor and not causing this) findings:
- in AuthMePlayerListener#onPreLogin we do dataSource#getAuth but then actually just read the realname -> we need to call a more specific method there to just retrieve the name/realname.
- AuthMePlayerListener#onPlayerMove calls Utils#checkAuth which calls PlayerCache#isAuthenticated so we need to make sure that this is efficient (and it is, it's a lookup in a hashmap, unless I'm missing something)

**Comment by ljacqu** [comment] 2016-02-21 11:06
@DNx5 You know the Guava stuff better than I do. Could it be this change? 
> https://github.com/AuthMe-Team/AuthMeReloaded/commit/c9b8846  Make cache RemovalListener sync (no longer use executor)

In #508 @Eisenbahn says it started around build nr. 750; that was on Feb 9th and the commit is from Feb 5th.

**Comment by DNx5** [comment] 2016-02-21 11:52
```
onPlayerMove(...) {
    plugin.getSpawnLocation(player);
}
```
Killed the main thread.

**Comment by sgdc3** [comment] 2016-02-21 12:03
As killed you mean blocked by a task, right?

**Comment by xyblues** [comment] 2016-02-21 12:15
@ljacqu
plugins:17 other plugins
player:I use BungeeCord,The total number of players to reach 140

**Comment by DNx5** [comment] 2016-02-21 12:17
maybe the database isn't responding. and because that check called in server thread, it crashed.
@xyblues is your database on the same server?

**Comment by xyblues** [comment] 2016-02-21 12:17
@DNx5  Yes

**Comment by DNx5** [comment] 2016-02-21 12:20
can you show us your config.yml?

**Comment by xyblues** [comment] 2016-02-21 12:23
[config.txt](https://github.com/Xephi/AuthMeReloaded/files/139602/config.txt)

**Comment by sgdc3** [comment] 2016-02-21 12:33
Ok, have you tried to enable the bungeecord hook and disable the kickPlayersBeforeStopping feature?

**Comment by sgdc3** [comment] 2016-02-21 12:35
I know this can't be the cause but we should try...

**Comment by xyblues** [comment] 2016-02-21 12:36
Ok,thanks.I will

**Comment by DNx5** [comment] 2016-02-21 12:39
For temporary fix, 
you could set allowMovement to false or set the allowedMovementRadius to 0

**Comment by DNx5** [comment] 2016-02-21 12:42
@sgdc3 kickPlayersBeforeStopping feature is not work.

**Comment by DNx5** [comment] 2016-02-21 12:50
@ljacqu 
we call it on pre login because we need the cache of PlayerAuth for next sync event.

**Comment by sgdc3** [comment] 2016-02-27 00:06
@xyblues Can you try latest build?

**Comment by DNx5** [comment] 2016-04-01 06:45
Closing this for no answer, and I remember `getSpawnLocation` method already improved.

**Closed by DNx5** 2016-04-01 06:45 UTC
