### ISSUE TITLE
ArrayIndexOutOfBounds if an email ends with @

### ISSUE THREAD

**Issue by Maxetto** [Xephi/AuthMeReloaded#1105] opened 2017-02-19 21:57 UTC
### What behaviour is observed:
Someone inserted a troll email without the second part after @.
That triggered an ArrayIndexOutOfBoundsException for the EmailValidator task
This should be an easy pick.

### Steps/models to reproduce:
1. Configure Email System
2. Register
3. Do /email add email@ email@

### Environment description
BungeeCord server + Spigot 1.8.8
MySQL 5.6

### AuthMe build number:
5.2 Stable (b1539)

### Error Log:
```
19.02 22:34:29 [Server] INFO EnderMarkYT issued server command: /email add email@ email@
19.02 22:34:29 [Server] WARN Exception in thread "Craft Scheduler Thread - 567" 
19.02 22:34:29 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.2-SNAPSHOT-b1539 generated an exception while executing task 66955
19.02 22:34:29 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
19.02 22:34:29 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
19.02 22:34:29 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
19.02 22:34:29 [Server] INFO at java.lang.Thread.run(Thread.java:745)
19.02 22:34:29 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
19.02 22:34:29 [Server] INFO at fr.xephi.authme.service.ValidationService.validateEmail(ValidationService.java:86)
19.02 22:34:29 [Server] INFO at fr.xephi.authme.process.email.AsyncAddEmail.addEmail(AsyncAddEmail.java:43)
19.02 22:34:29 [Server] INFO at fr.xephi.authme.process.Management.lambda$performAddEmail$8(Management.java:84)
19.02 22:34:29 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
19.02 22:34:29 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
19.02 22:34:29 [Server] INFO ... 3 more
```

**Comment by sgdc3** [comment] 2017-02-19 22:32
Duplicate of #1079

**Comment by sgdc3** [comment] 2017-02-19 22:32
Already fixed ;) Thank you.

**Closed by sgdc3** 2017-02-19 22:32 UTC
Labels: duplicate

**Comment by Maxetto** [comment] 2017-02-19 22:36
Not really. I think it's better to do this:
```
if (!email.contains("@") || email.split("@").length != 2 || "your@email.com".equalsIgnoreCase(email))
  return false;
```

With your fix it would error even with "@email"

**Comment by Maxetto** [comment] 2017-02-19 22:37
Anyway I think it should be better to use a Regex in general.

**Comment by ljacqu** [comment] 2017-02-20 06:11
No, please no regex to validate the email. This opens a door to hell.

**Comment by ljacqu** [comment] 2017-02-20 06:13
We have a story to purge users that have never logged in after email registration. Besides that, if they provide an invalid email it's really their problem (only affects email recovery). 
I'd be all for checking that something follows the `@` but please no regex

**Comment by sgdc3** [comment] 2017-02-20 06:38
lol
