### ISSUE TITLE
MySQL Syntax Error

### ISSUE THREAD

**Issue by SureWay** [Xephi/AuthMeReloaded#653] opened 2016-04-13 17:06 UTC
Hi,

i get a MySQL Syntax error when i try to login. ((AuthMe-5.2-SNAPSHOT-spigot.jar))

`[19:02:39] [Server thread/WARN]: [AuthMe] Error during SQL operation: [MySQLSyntaxErrorException]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM wcf1_user WHERE username='sureway'' at line 1`

with authme 3.4 works. i use wbb4.

**Comment by sgdc3** [comment] 2016-04-13 19:11
Could you post your config? ;) Thanks

**Comment by ljacqu** [comment] 2016-04-13 19:52
+ if you have an authme.log the entire error would be interesting

**Comment by SureWay** [comment] 2016-04-13 21:19
Config: http://pastebin.com/KA22Xe1z
Log: http://pastebin.com/ih71RsRy

**Comment by ljacqu** [comment] 2016-04-14 07:27
Thanks for the info. Did this only happen when you switched to WB4?
I created a temp `/authme pw` command on a branch that goes through our `API` class the same way as the plugin you're using does. At first I thought there was a problem with how the username is inserted into the SQL query, but having had a second look at the logs I wonder if the table name is causing trouble. I'll report back.

**Comment by ljacqu** [comment] 2016-04-14 07:36
The issue is that MySQL#getPassword is not aware that `col.SALT` can be an empty string. Same for SQLite#getPassword

**Comment by ljacqu** [comment] 2016-04-14 09:52
@SureWay The error should be fixed as of build nr. 933 http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by SureWay** [comment] 2016-04-14 19:12
Thanks!

but sometimes i get this error

```
[04-14 20:58:18]: Connection arguments loaded, Hikari ConnectionPool ready!
[04-14 20:58:18]: MySQL setup finished
[04-14 20:58:18]: Hooked successfully into Essentials
[04-14 20:58:18]: Hooked successfully into Multiverse-Core
[04-14 20:58:18]: [LICENSE] This product uses data from the GeoLite API created by MaxMind, available at http://www.maxmind.com
[04-14 20:58:18]: Development builds are available on our jenkins, thanks to f14stelt.
[04-14 20:58:18]: Do you want a good game server? Look at our sponsor GameHosting.it leader in Italy as Game Server Provider!
[04-14 20:58:18]: AuthMe 5.2-SNAPSHOT-b935 correctly enabled!
[04-14 20:58:34]: ERROR: Could not read number of rounds in '$2a$08$MKXcEKdI3cVCim8e59iH.OY09gd5V5f2U.c66HrKS5dFw9gqr2/ym for CryptPBKDF2Django [NumberFormatException]: For input string: "2a"
[04-14 20:58:34]: java.lang.NumberFormatException: For input string: "2a"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:492)
	at java.lang.Integer.parseInt(Integer.java:527)
	at fr.xephi.authme.security.crypts.CryptPBKDF2Django.comparePassword(CryptPBKDF2Django.java:32)
	at fr.xephi.authme.security.PasswordSecurity.methodMatches(PasswordSecurity.java:93)
	at fr.xephi.authme.security.PasswordSecurity.compareWithAllEncryptionMethods(PasswordSecurity.java:71)
	at fr.xephi.authme.security.PasswordSecurity.comparePassword(PasswordSecurity.java:47)
	at fr.xephi.authme.security.PasswordSecurity.comparePassword(PasswordSecurity.java:40)
	at fr.xephi.authme.api.API.checkPassword(API.java:124)
	at eu.paradice.paraauthme.paraauthme.onPlayerCommandPreprocessEvent(paraauthme.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1342)
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185)
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45)
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721)
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ljacqu** [comment] 2016-04-17 06:18
@SureWay Sorry, I totally missed that you replied. Thanks for the response, in that case I wager we can close this.

You're getting the error you posted because you have `supportOldPasswordHash` set to `true`. This means every time a player does `/login`, we first try the current password hash and if that fails, we go through _all_ of the hashes that AuthMe supports.
In the case of Bcrypt & friends it has a format where it expects a number at some point. Obviously if the password has been hashed with a different algorithm the format might not comply with that. We catch it and log it, though, admittedly, it's a little overkill that the entire stack trace is printed. 
But long story short this error is fine and nothing to worry about :) You should never get it with `supportOldPasswordHash: false`

**Closed by ljacqu** 2016-04-17 06:19 UTC
Labels: bug, please verify

**Comment by sgdc3** [comment] 2016-04-17 10:44
Maybe if the supportOldPasswordHash option is enabled we should print a message before any hash related stacktrace :/

**Comment by sgdc3** [comment] 2016-04-17 10:44
@ljacqu

**Comment by ljacqu** [comment] 2016-04-17 11:28
I've opened another issue so we can keep this as a bug, with the original title. Things get confusing otherwise.

**Comment by sgdc3** [comment] 2016-04-17 11:43
You're right, sorry ;)
