### ISSUE TITLE
Unregister from other worlds bug

### ISSUE THREAD

**Issue by NewBestX** [Xephi/AuthMeReloaded#821] opened 2016-07-02 20:26 UTC
Hi!
If I do /unregister from any world but the one that contains the authme spawnpoint (/autme setspawn) I get this error:

```
[23:19:46] [Craft Scheduler Thread - 9/WARN]: Exception in thread "Craft Scheduler Thread - 9" 
[23:19:46] [Craft Scheduler Thread - 9/WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.2-SNAPSHOT-b1176 generated an exception while executing task 85
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Asynchronous player tracker clear!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
	at net.minecraft.server.v1_10_R1.EntityTrackerEntry.clear(EntityTrackerEntry.java:555)
	at net.minecraft.server.v1_10_R1.EntityTracker.untrackPlayer(EntityTracker.java:242)
	at net.minecraft.server.v1_10_R1.PlayerList.moveToWorld(PlayerList.java:560)
	at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.teleport(CraftPlayer.java:486)
	at org.bukkit.craftbukkit.v1_10_R1.entity.CraftEntity.teleport(CraftEntity.java:226)
	at fr.xephi.authme.util.Utils.teleportToSpawn(Utils.java:70)
	at fr.xephi.authme.process.unregister.AsynchronousUnregister.unregister(AsynchronousUnregister.java:59)
	at fr.xephi.authme.process.Management$4.run(Management.java:77)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

```

If I do /authme setspawn in another world, I will be able to do /unregister from there without any problems, but the problem will appear on the previous world.
After this happens, the account is removed, but the player remains in-game, gets no message and is not affected in any way until he disconnects.

I am using Multiverse. Tested with AuthMe Build #1176.

**Comment by sgdc3** [comment] 2016-07-11 20:29
@NewBestX please try again with latest build, a commit from @ljacqu may have fix this.

**Comment by ljacqu** [comment] 2016-08-04 20:53
Since there's no reply by @NewBestX , assigning to me to test if i can reproduce this tomorrow

**Comment by Twonox** [comment] 2016-08-14 18:56
I receive any errors when I do /unregister (in all worlds). I think that's fixed.

**Comment by sgdc3** [comment] 2016-08-14 19:00
@Twonox could you post the error?

**Comment by Twonox** [comment] 2016-08-14 19:09
I don't receive error messages

**Comment by sgdc3** [comment] 2016-08-14 19:16
>I receive any errors when I do /unregister (in all worlds).

**Comment by sgdc3** [comment] 2016-08-14 19:16
Ah i don't receive any errors ;)

**Comment by Twonox** [comment] 2016-08-14 19:17
sorry x)

**Closed by Twonox** 2016-08-14 19:17 UTC
Labels: bug
