### ISSUE TITLE
Fly mode before login

### ISSUE THREAD

**Issue by elessday** [Xephi/AuthMeReloaded#530] opened 2016-02-15 16:24 UTC
Hello,

I am looking for a logout flymod, is it possible ?
The server is actually in survival mod, but i want only the fly mod before the login.

Thank you in advance.

**Comment by sgdc3** [comment] 2016-02-15 16:27
Duplicate of #510

**Closed by sgdc3** 2016-02-15 16:27 UTC

**Comment by elessday** [comment] 2016-02-15 16:31
It is not the same problem >.<

**Comment by ljacqu** [comment] 2016-02-15 16:35
#510 suggests putting players back down to the ground—you suggest enabling flight. Both are about the same _problem_ though, and I'd wager your proposition is better (easier implementation + foolproof for water)

**Comment by elessday** [comment] 2016-02-15 16:36
So, there's no solution ?

**Comment by ljacqu** [comment] 2016-02-15 16:38
None atm. The problem will be tackled with #510. i think Github offers a way to follow specific issues.
