### ISSUE TITLE
Tp or Afk and Login

### ISSUE THREAD

**Issue by TheIntelloBox** [Xephi/AuthMeReloaded#692] opened 2016-05-05 15:30 UTC
Hello,

Sometimes, my players must be login whereas they're playing and they were loginned ? 
The same issue when do a tp sometimes.

**Comment by sgdc3** [comment] 2016-05-05 16:18
Duplicate of #688

**Closed by sgdc3** 2016-05-05 16:18 UTC
Labels: duplicate

**Comment by TheIntelloBox** [comment] 2016-05-16 17:04
On 10 minutes, I must login 6 times !!!

**Comment by sgdc3** [comment] 2016-05-16 21:24
Should have been fixed in the latest build, you can download it from our buildserver
