### ISSUE TITLE
/Authme ChangePassword is bugged.

### ISSUE THREAD

**Issue by Done84** [Xephi/AuthMeReloaded#298] opened 2015-12-03 20:20 UTC
Authme Change password is bugged. When trying to change a users password i get this error:
http://i.imgur.com/eEd6SJE.png

**Comment by ljacqu** [comment] 2015-12-03 20:32
The password is positively not your username? I can't seem to reproduce this

**Comment by Done84** [comment] 2015-12-03 20:54
Nop. Its not, even in the console this happens. With any password.

**Comment by ljacqu** [comment] 2015-12-03 20:56
In your configuration, under `Restriction` there is a setting `allowedPasswordCharacters`. Would you mind sharing its value? Most likely it's set to something that is too restrictive.

By default it's `allowedPasswordCharacters: '[\x21-\x7E]*'`

**Comment by d1One** [comment] 2015-12-03 21:02
allowedPasswordCharacters: '[a-zA-Z0-9_?!@+&-]*'

Strange, i never changed that, im terrible with regex

**Comment by ljacqu** [comment] 2015-12-03 21:05
Thanks for the response. `?` is a special character in regex that should probably be escaped; I wonder if it shouldn't be `\\?` or `\?`. Easiest is probably to revert to the default I posted unless you're bound to this pattern; it will allow all printable ASCII characters besides the space " " (for obvious reasons).

**Comment by d1One** [comment] 2015-12-03 21:09
Yeah usually i think its \?. Anyway i used your settings and its working now. I have no idea where that regex came from, maybe something happen during the update from the v5 to this new build and put that there.

The error message should be "ilegal characters" instead of the name thing, that might confuse new players trying to register. Thanks for your help!

**Comment by ljacqu** [comment] 2015-12-03 21:14
I'm glad that could resolve your issue – sorry for the trouble. Possibly this is the setting that was used in prior versions of AuthMe.

The code changes I referenced to this issue update the error message to something more meaningful. That was definitely a misleading error message and so it's great that you've reported it!

My guess is `\\?` because it first goes through the YAML parser that might think `\?` is some sort of character escape. Only after it's been parsed to `\?` do we compile it to a regular expression. But I'm not familiar with such fine details of the YAML syntax or parser.

**Comment by Xephi** [comment] 2015-12-04 16:28
Sorry for that problem and i hope it's fixed now :) , i change the error message from password error nickname to password not match, thanks for report anyway

**Closed by Xephi** 2015-12-04 16:28 UTC
