### ISSUE TITLE
Repo not working

### ISSUE THREAD

**Issue by Trojaner25** [Xephi/AuthMeReloaded#471] opened 2016-01-25 18:52 UTC
The repo at http://ci.xephi.fr/plugin/repository/everything/ does not work correctly.

> [ERROR] Failed to execute goal on project SinkBans: Could not resolve dependencies for project de.static_interface:SinkBans:jar:1.3: Could not transfer artifact fr.xephi:authme:jar:5.2-20160123.133212-699 from/to authme-repo (http://ci.xephi.fr/plugin/repository/everything/): GET request of: fr/xephi/authme/5.2-SNAPSHOT/authme-5.2-20160123.133212-699.jar from authme-repo failed: Premature end of Content-Length delimited message body (expected: 1753162; received: 109742 -> [Help 1]

Seems like downloads get aborted

**Comment by sgdc3** [comment] 2016-01-25 19:25
Yeah i know.... Our vps has 100% of hdd usage due to a bug. We need to wait @Xephi to fix it...

**Comment by sgdc3** [comment] 2016-01-26 23:18
Fixed

**Comment by sgdc3** [comment] 2016-01-26 23:18
@Xephi

**Comment by sgdc3** [comment] 2016-01-26 23:22
Nope still unavariable..

**Comment by sgdc3** [comment] 2016-01-26 23:22
@Xephi

**Comment by games647** [comment] 2016-01-27 13:29
Now my builds fails too :worried:

Isn't it possible to delete some older version in order to free some spaces?

**Comment by sgdc3** [comment] 2016-01-27 14:52
no, there is a glitched log file

**Comment by games647** [comment] 2016-01-28 10:42
@sgdc3 Is it fixed, because my builds works again.

**Comment by sgdc3** [comment] 2016-01-28 10:48
@games647 yeah but it's not stable still100gb of usage

**Comment by Xephi** [comment] 2016-01-28 11:17
I've checked directly on vps and the biggest directory i've found has 1Gb max, idk where it comes from, if you have some information tell me

**Comment by sgdc3** [comment] 2016-01-28 15:15
Don't you remember? There is a glitched jenkins tmp file.

**Comment by Xephi** [comment] 2016-01-29 09:08
I remember , but we have a cron task that rm it each minutes T.T

**Comment by sgdc3** [comment] 2016-01-29 12:52
I know, probably after the update the file path changed

**Comment by Xephi** [comment] 2016-01-29 14:32
I've found the problem and it's now fixed

**Closed by Xephi** 2016-01-29 14:32 UTC

**Comment by sgdc3** [comment] 2016-01-29 16:16
What was the cause? @Xephi

**Comment by Xephi** [comment] 2016-01-29 16:21
A file at /var/log/daemon.log was to big

**Comment by sgdc3** [comment] 2016-01-29 19:12
Are you sure? http://ci.xephi.fr/plugin/disk-usage/
