### ISSUE TITLE
[TEMP-FIXED] Some players are unable to walk after login

### ISSUE THREAD

**Issue by jomjonejame** [Xephi/AuthMeReloaded#890] opened 2016-08-08 03:38 UTC
Players can't moving in Authhme DevBuild #1271
Sample on video : https://www.youtube.com/watch?v=h1qH-hZM_-Y

But version "AuthMe 5.2 BETA 3" can it
Sample on video : https://www.youtube.com/watch?v=x24jj5fVVgg

and last version #1272 found error in console
logs file : http://pastebin.com/Ya52F8jp

**Comment by Twonox** [comment] 2016-08-08 12:35
Your video are private.

**Comment by sgdc3** [comment] 2016-08-08 12:40
@jomjonejame Could you post your config?

**Comment by jomjonejame** [comment] 2016-08-08 13:25
@Twonox  Sorry ... i'm enabled to public. plz try agin

**Comment by jomjonejame** [comment] 2016-08-08 13:26
@sgdc3  Config file : http://pastebin.com/mWfsc3Re

**Comment by sgdc3** [comment] 2016-08-08 13:49
@jomjonejame I removed the file as is contains your password, please remove it and post it again

**Comment by jomjonejame** [comment] 2016-08-08 13:57
@sgdc3  Thank you
http://pastebin.com/JbxhpqKQ

**Comment by Twonox** [comment] 2016-08-08 17:55
You can set `removeSpeed: false` to fix 'no walk' problem.
@sgdc3 You can't fix that ? If we would use removeSpeed...

**Comment by sgdc3** [comment] 2016-08-08 19:15
Please change the name to something more related to the issue

**Comment by tuanjr** [comment] 2016-08-08 19:37
i'm confirm this issues, but with my server, not all player can't move, only some player can't move after login.
My authme version: build 1271
server: 1.9.2

**Comment by Twonox** [comment] 2016-08-08 20:26
#783 Hmm ? What had you do to break it? xD

**Comment by sgdc3** [comment] 2016-08-08 20:29
@Twonox idk

**Comment by Twonox** [comment] 2016-08-08 20:30
I will search the build that cause this problem :)

**Comment by sgdc3** [comment] 2016-08-08 20:32
@Twonox Thank you :D

**Comment by Twonox** [comment] 2016-08-08 20:55
Finded, Build 1183: http://ci.xephi.fr/job/AuthMeReloaded/1183

**Comment by Twonox** [comment] 2016-08-08 20:59
Build 1181 doesn't have this problem.

**Comment by sgdc3** [comment] 2016-08-08 21:01
1182?

**Comment by Twonox** [comment] 2016-08-08 21:02
There is no change in this build

**Comment by sgdc3** [comment] 2016-08-08 21:03
right, thank you

**Comment by Twonox** [comment] 2016-08-08 21:04
#592

**Comment by jomjonejame** [comment] 2016-08-09 00:55
@tuanjr Yes correct

**Comment by jomjonejame** [comment] 2016-08-09 00:57
@sgdc3 , @Twonox This problem has been fixed yet?

**Comment by sgdc3** [comment] 2016-08-09 01:13
Not yet but it's our priority

**Comment by tuanjr** [comment] 2016-08-09 05:46
i have more information about this issues:
i have 2 lobby, with some player, they can't walk in both 2 lobby, but some player, they only can't walk in 1 lobby, not all.

**Comment by Twonox** [comment] 2016-08-09 07:57
@sgdc3 You can't remove Dnx's change ? His "fix" for fly speed break your right fix.

**Comment by sintaxcz** [comment] 2016-08-09 09:43
Hello i have same problem on my server (Thermos 1.7.10-b57) premium players dont have problem but 90% of cracked players have this issue

**Comment by sgdc3** [comment] 2016-08-09 13:02
@Twonox DNx5's commit fixed other huge issues, we need to find out the cause. Atm you should turn off the removeSpeed feature.

**Comment by Twonox** [comment] 2016-08-09 13:40
@sgdc3, @ljacqu had removed your code.

**Comment by Twonox** [comment] 2016-08-09 14:03
@jomjonejame 

( you can remove `HideTablistBeforeLogin` from your config (if you use latest build) because it's removed from Authme, or set `false` to have no issue with it (is you use beta 3))

Could you test Build 1183 and 1181 please ? (With `removeSpeed: true`)
http://ci.xephi.fr/job/AuthMeReloaded/1183/
http://ci.xephi.fr/job/AuthMeReloaded/1181/

**Comment by sintaxcz** [comment] 2016-08-09 14:15
turn off remove speed do nothing on builds 1183+ with Thermos 1.7.10 b57 tested with 3 cracked players

**Comment by sgdc3** [comment] 2016-08-09 14:34
@Twonox He moved the code, it's still there. The issue is about the cache

**Comment by sgdc3** [comment] 2016-08-09 16:05
Should have been temp-fixed. The issue is that if the player moves while he is joining the server our listener set his speed to 0, before our cache saves the speed.

**Comment by sgdc3** [comment] 2016-08-09 16:06
@Twonox Does it work now?

**Comment by Twonox** [comment] 2016-08-09 16:42
Yes but `removeSpeed: false` doesn't work

**Comment by sgdc3** [comment] 2016-08-09 16:50
@Twonox That because the players have speed 0 in the world save, keep it enabled and everyone will get the speed back on login

**Comment by Twonox** [comment] 2016-08-09 17:00
@jomjonejame @sintaxcz @tuanjr 
Could you also test latest build ?

**Comment by rErEaT** [comment] 2016-08-09 17:26
what happens if I write this?

    # Force these commands after /login, without any '/', use %p to replace with player name
    forceCommands: []
    # Force these commands after /login as service console, without any '/'. Use %p to replace with player name
    forceCommandsAsConsole: speed walk 1 %p, speed fly 1 %p
    # Force these commands after /register, without any '/', use %p to replace with player name
    forceRegisterCommands: []
    # Force these commands after /register as a server console, without any '/'. Use %p to replace with player name
    forceRegisterCommandsAsConsole: speed walk 1 %p, speed fly 1 %p

**Comment by sgdc3** [comment] 2016-08-09 17:30
1 isn't the default speed if i remember well

**Comment by rErEaT** [comment] 2016-08-09 17:33
but @sgdc3 it should work?
so is it good? "forceRegisterCommandsAsConsole: speed walk 1 %p, speed fly 1 %p"
hope will run these commands

**Comment by sgdc3** [comment] 2016-08-09 17:42
yeah it works

**Comment by sgdc3** [comment] 2016-08-09 17:42
but the easiest fix is to keep removeSpeed to true

**Comment by sgdc3** [comment] 2016-08-09 17:43
with latest build

**Comment by rErEaT** [comment] 2016-08-09 17:43
oh okay, but the jenkins says its unstable :S

**Comment by sgdc3** [comment] 2016-08-09 17:43
wait, i'm pushing a stable build ;)

**Comment by rErEaT** [comment] 2016-08-09 17:46
by the way I think the default speed is 1 :)

**Comment by sgdc3** [comment] 2016-08-09 17:48
for essentials, at code level the default speed is 2 :)

**Comment by rErEaT** [comment] 2016-08-09 17:49
oh! :D

**Comment by tuanjr** [comment] 2016-08-09 18:51
I'm just try latest build 1282, issues still not fixed!

**Comment by Twonox** [comment] 2016-08-09 19:15
Could you test Build 1183 and 1181 please ? (With removeSpeed: true)
http://ci.xephi.fr/job/AuthMeReloaded/1183/
http://ci.xephi.fr/job/AuthMeReloaded/1181/

**Comment by tuanjr** [comment] 2016-08-09 19:20
@Twonox 
Just test:
1181 work fine, player can walk
1183 player CAN'T walk

**Comment by sgdc3** [comment] 2016-08-09 19:22
@tuanjr You must use 1282 with removeSpeed: true

**Comment by tuanjr** [comment] 2016-08-09 19:24
it is default, i never change it.

**Comment by friishon** [comment] 2016-08-11 12:49
the solution is write /logout and then login
i have the same problem, i use mysql and use bungee cord
i have this problem when i change the server

**Comment by Twonox** [comment] 2016-08-11 14:08
With latest build ?

**Comment by friishon** [comment] 2016-08-11 15:05
that version
http://ci.xephi.fr/job/AuthMeReloaded/1282/

**Comment by Twonox** [comment] 2016-08-11 16:03
If you use this build http://ci.xephi.fr/job/AuthMeReloaded/1280/ with `removeSpeed: false` what happens ?

**Comment by Twonox** [comment] 2016-08-11 16:04
De you have `removeSpeed: true` with build 1282 ?

**Comment by friishon** [comment] 2016-08-11 16:17
yes i have removeSpeed: true
i haven't use de build 1280 yet
i use authme bridge and to solve the problem i put  allowMovement: true and i can move
i only put this opcion on the server survival, skywars and minigames
on lobby have this  allowMovement: false and i can move
sorry about my english, i'm from spain

**Comment by jomjonejame** [comment] 2016-08-11 16:48
#1282 Has not been resolved.
now some players has new registered. can't move

**Comment by Twonox** [comment] 2016-08-11 19:25
If you use Build 1280 with `removeSpeed: false` there is less problem or no ?

**Comment by friishon** [comment] 2016-08-12 16:24
i have the same problem using Build 1280 and removeSpeed: false
the problem are in sqlite and mysql

**Comment by rErEaT** [comment] 2016-08-13 11:24
If you are using Essentials, I will sure solve the problem.

**Comment by friishon** [comment] 2016-08-13 16:52
using that
forceCommandsAsConsole: 
- 'speed walk 1 %p'
- 'speed fly 1 %p'
forceRegisterCommandsAsConsole: 
- 'speed walk 1 %p'
- 'speed fly 1 %p'
i can't move

**Comment by sgdc3** [comment] 2016-08-13 21:48
@rErEaT @jomjonejame @Twonox Does it work if you set the bungeecord hook setting to false?

**Comment by rErEaT** [comment] 2016-08-13 21:50
no.

Sometimes still bug :/

**Comment by Twonox** [comment] 2016-08-14 00:14
I don't use Bungeecord and I don't have this problem. For me it's fixed with your Temp-Fix.

**Comment by rErEaT** [comment] 2016-08-14 00:50
hmm then authme should check the speed, if it 0, authme will restore

**Comment by sgdc3** [comment] 2016-08-14 01:53
it's exactly what i did xD

**Comment by sgdc3** [comment] 2016-08-14 01:54
the only reason the speed is not reatored can be that the limbo cache is null, this is an issue that happens only with the bungeecord hook

**Comment by rErEaT** [comment] 2016-08-14 01:55
oh, btw i think u dont check the fly speed, because my moderator reported this :D

**Comment by sgdc3** [comment] 2016-08-14 01:58
i do

**Comment by sgdc3** [comment] 2016-08-14 01:59
look: https://github.com/AuthMe/AuthMeReloaded/commit/efe62beccdaa7ca27ec77314862744d146f9c9ef

**Comment by DNx5** [comment] 2016-08-14 04:43
in the first video, its looks like not speed problem, more like the player is not logged in. the player movement got cancelled.

**Comment by rErEaT** [comment] 2016-08-14 11:23
oh then sorry @sgdc3 !

**Comment by sgdc3** [comment] 2016-08-14 11:26
could you record a video with the latest version?

**Comment by friishon** [comment] 2016-08-16 03:31
i can't move with this build http://ci.xephi.fr/job/AuthMeReloaded/1287/
and the fix now block me, and i have to write /logout and then /login again

**Comment by sgdc3** [comment] 2016-08-16 08:16
does it happen only if you connect via bungee or also on firectly connected servers?

**Comment by friishon** [comment] 2016-08-16 11:53
via bungee, but i think the problem is the authme bridge

**Comment by sgdc3** [comment] 2016-08-16 12:37
could you try without it?

**Comment by friishon** [comment] 2016-08-16 18:31
i try and i can't move
the problem i have, is when i change the server
the server said that i already in the server but i haven't iventory and i have to write /logout and then /login password to move

**Comment by friishon** [comment] 2016-08-17 01:25
the frist capture is the server: lobby, i haven' problem in this server
![recorte1](https://cloud.githubusercontent.com/assets/19889173/17721318/9e78fa32-6429-11e6-8a83-fc1a17d775e4.PNG)
the second capture is my survival server, but i can't move, and i haven't got the inventory, i have to write /logout
![recorte2](https://cloud.githubusercontent.com/assets/19889173/17721320/9e858c20-6429-11e6-96cd-0e52472cfc16.PNG)
the third capture is my relogin after write /logout and /login
![recorte3](https://cloud.githubusercontent.com/assets/19889173/17721319/9e8415e8-6429-11e6-9bb4-012274ba25d1.PNG)

**Comment by friishon** [comment] 2016-08-21 03:48
http://ci.xephi.fr/job/AuthMeReloaded/1290/
this version, has the same problem, but now i can´t move in every server
even put
forceCommandsAsConsole: 
- 'speed walk 1 %p'
- 'speed fly 1 %p'
forceRegisterCommandsAsConsole: 
- 'speed walk 1 %p'
- 'speed fly 1 %p'

the problem is: i have to relogin for walk and have inventory

**Comment by Twonox** [comment] 2016-10-01 13:21
I'm now using Bungee & Authme, and I don't have speed problem.

**Comment by sgdc3** [comment] 2016-12-26 00:36
should have been fixed ;)

**Closed by sgdc3** 2016-12-26 00:36 UTC
Labels: bug, bungeecord, critical
