### ISSUE TITLE
Authme doesnt let people login

### ISSUE THREAD

**Issue by jugtej** [Xephi/AuthMeReloaded#961] opened 2016-09-30 11:09 UTC
I am using authme and sometimes when people put in the login command the server doesnt register it and it also sometimes happens to everyone on the server. this is what happens 

09:36:30 <>                       Player KeraYamato disconnected (§4Login timeout exceeded, you have been kicked from the server, please try again!)
09:36:00 <>                       Player KeraYamato connected
09:35:22 <>                       Player KeraYamato disconnected (§4Login timeout exceeded, you have been kicked from the server, please try again!)
09:34:51 <>                       Player KeraYamato connected
09:32:15 <>                       Player KeraYamato disconnected (§4Login timeout exceeded, you have been kicked from the server, please try again!)
09:31:45 <>                       Player KeraYamato connected
09:31:18 <>                       Player KeraYamato disconnected (§4Login timeout exceeded, you have been kicked from the server, please try again!)
09:30:48 <>                       Player KeraYamato connected
09:27:01 <>                       Player MineKiller24 disconnected (Internal Exception: java.io.IOException: Error while read(...): Connection reset by peer)
09:26:48 <>                       Player MineKiller24 connected
09:26:08 <>                       Player jugtej2001 disconnected (§4Login timeout exceeded, you have been kicked from the server, please try again!)
09:25:37 <>                       Player jugtej2001 connected
09:17:42 <>                       Player jugtej2001 disconnected (§4Login timeout exceeded, you have been kicked from the server, please try again!)
09:17:12 <>                       Player jugtej2001 connected
09:15:09 <LitterBoy>              a
09:15:00 <>                       Player jugtej2001 disconnected (§4Login timeout exceeded, you have been kicked from the server, please try again!)
09:14:30 <>                       Player jugtej2001 connected
09:14:15 <>                       Player jugtej2001 disconnected (§4Login timeout exceeded, you have been kicked from the server, please try again!)
09:13:45 <>                       Player jugtej2001 connected
09:07:53 <>                       Player GhostOfDusk disconnected (Internal Exception: java.io.IOException: Error while read(...): Connection reset by peer)
09:07:38 <>                       Player GhostOfDusk connected
09:07:33 <>                       Player GhostOfDusk disconnected (§4Login timeout exceeded, you have been kicked from the server, please try again!)
09:07:26 <>                       Player KeraYamato disconnected (§4Login timeout exceeded, you have been kicked from the server, please try again!)
09:07:26 <>                       Player MineKiller24 disconnected (Disconnected)
09:07:22 <LitterBoy>              a
09:07:10 <>                       Player MineKiller24 connected
09:07:03 <>                       Player GhostOfDusk connected
09:06:56 <>                       Player KeraYamato connected
09:06:55 <>                       Player GhostOfDusk disconnected (§4Login timeout exceeded, you have been kicked from the server, please try again!)
09:06:46 <LitterBoy>              ghost u cant login?
09:06:43 <>                       Player MineKiller24 disconnected (§4Login timeout exceeded, you have been kicked from the server, please try again!)
09:06:25 <>                       Player GhostOfDusk connected
09:06:17 <>                       Player GhostOfDusk disconnected (§4Login timeout exceeded, you have been kicked from the server, please try again!)
09:06:13 <>                       Player MineKiller24 connected
09:06:11 <>                       Player KeraYamato disconnected (§4Login timeout exceeded, you have been kicked from the server, please try again!)
09:06:04 <>                       Player MineKiller24 disconnected (Disconnected)
09:05:47 <>                       Player GhostOfDusk connected
09:05:41 <>                       Player GhostOfDusk disconnected (§4Login timeout exceeded, you have been kicked from the server, please try again!)
09:05:41 <>                       Player KeraYamato connected
09:05:35 <>                       Player KeraYamato disconnected (§4Login timeout exceeded, you have been kicked from the server, please try again!)
09:05:24 <LitterBoy>              GhostOfDusk
09:05:11 <>                       Player GhostOfDusk connected

**Comment by jeremy100** [comment] 2016-09-30 11:11
Please review your message and write it well because it is hard to understand

**Comment by jugtej** [comment] 2016-09-30 11:12
sorry jeremy100 kinda new to using github so i had messed up

**Comment by jeremy100** [comment] 2016-09-30 11:15
Okay, go into the folder and copy the latest AuthMe that generated the "Authme.log" file please. But at first glance I think it can be for lack of permits. You use a plugin permission?

**Comment by jugtej** [comment] 2016-09-30 11:28
http://pastebin.com/6cjR0LPD
i am using a permission plugins but even op players have this issue.

**Comment by jeremy100** [comment] 2016-09-30 11:30
Unfortunately I can not find the problem. I hope that project managers can help you better than me. sorry

**Comment by sgdc3** [comment] 2016-09-30 11:31
Please post your config and your plugin list?

**Comment by jugtej** [comment] 2016-09-30 11:57
the config is http://pastebin.com/wRmZYjQH   and the plugins are below
![image](https://cloud.githubusercontent.com/assets/22541099/18990924/f62ecc80-8732-11e6-8829-648c6dbf501d.png)
![image](https://cloud.githubusercontent.com/assets/22541099/18990938/18104360-8733-11e6-8c54-fa2ef22d2f05.png)

**Comment by ljacqu** [comment] 2016-09-30 13:14
> [09-30 02:31:57]: Debug: AuthMe-CacheLoader:REFRESH litterboy

Could you try to update to a newer version please?
http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by jugtej** [comment] 2016-09-30 13:31
i have tried it on the latest version which is 5.2 september build and i still have the issue so i am now using 5.2 beta 3 which is working smoother but im still having the issue

**Comment by ljacqu** [comment] 2016-09-30 20:24
OK, let's take a step back:

> I am using authme and sometimes when people put in the login command the server doesnt register it

-> What does "doesn't register" mean? Does the server send back a "permission denied" message or does the server literally NOT respond to the command? 

What happens with other commands (another AuthMe command, e.g. `/register`, vs. a command not from AuthMe, e.g. `/spawn` or `/hub`).

**Comment by jugtej** [comment] 2016-10-01 07:29
ok so ill explain it.  i join the server and then i see the /login <password > command  it like spams twice before i actually enter my password it and after i put the login command in. nothing happens. the login messages keeps on spamming and i  dont get logged in. at first i thought it was lag. i remove out things to reduce lag too but i still have the issue and not only me but other people also get this

**Comment by ljacqu** [comment] 2016-10-01 07:43
What happens with other commands (another AuthMe command, e.g. /register, vs. a command not from AuthMe, e.g. /spawn or /hub).

**Comment by jugtej** [comment] 2016-10-01 07:46
ok so no message comes up and then i get kicked although if i try to normal chat i get a message which says in order to chat you must be authenticated

**Comment by ljacqu** [comment] 2016-10-01 07:50
So both another AuthMe command as well as some other command just gets ignored?
If the chat block works as you said, I wonder if there's a conflict with another plugin that handled all commands too aggressively. Is there any suspect that comes to your mind?

**Comment by jugtej** [comment] 2016-10-01 07:52
at the very first when i had added authme. it has aggravated no cheat plus's captcha

**Comment by jugtej** [comment] 2016-10-01 07:57
i have opened up the authme.log and near the top i saw this 
[09-30 02:30:50]: SQLite driver loaded
[09-30 02:30:50]: SQLite Setup finished
[09-30 02:30:50]: Unhooked from Permissions!
[09-30 02:30:50]: Hooked into Vault!
[09-30 02:30:50]: Hooked successfully into Essentials
[09-30 02:30:50]: Hooked successfully into Multiverse-Core

now im not a programmer or anything but i dont think that permission being unhooked from authme is a good sign

**Comment by ljacqu** [comment] 2016-10-01 08:25
The unhooked message is a bad debug message that has been fixed in newer builds :) It means nothing, we're "unhooking from nothing" at the start. But good catch.

I added some debug messages to a version of AuthMe whose JAR you can download here: https://github.com/ljacqu/AuthMeReloaded/tree/961-command-event-debug/samples (legacy or spigot depending on the one you need)
In the config of newer versions you'll find:
```yml
    # Log level: INFO, FINE, DEBUG. Use INFO for general messages,
    # FINE for some additional detailed ones (like password failed),
    # and DEBUG for debugging
    logLevel: 'FINE'
```
Please change that to `DEBUG`. Every time a command is sent to the server AuthMe handles the command event and determines whether the player may or may not run this command. It will look something like this and will also get logged into authme.log:
```
[AuthMe] Debug: Allowing command '/l' by player 'CraftPlayer{name=ljacqu}'
```

It would be really cool if you could run this and hit the server with a few commands. My guess is that there will be no debug messages because another plugin is catching the event before us.

**Comment by jugtej** [comment] 2016-10-01 09:03
thank you. ill be running the file and testing for the file for a while

**Comment by ljacqu** [comment] 2016-10-01 09:12
Excellent, thank you; I look forward to your results. Should you not find any debug messages<sup>1</sup> I would suggest to remove some "suspect" plugins—if no command event is coming to AuthMe we need to find which plugin is interfering, and then we can see how to best handle it (whether it's a problem on the other plugin's side, or on ours).

-- 

<sup>1</sup> I probably should have included another message so we're sure the debug logging works, but anyway it just depends on that setting

**Comment by jugtej** [comment] 2016-10-01 19:55
well i havent been able to test it much but i did ask a few players about it and according to them authme was working flawless so i would like to say thank you cause this issue was really bugging me

**Comment by ljacqu** [comment] 2016-10-01 20:00
Thanks for the update. Weird, maybe we have something weird going on in that older version you're using that has been fixed more recently. If it occurs again you know where we'll continue :wink: Is this OK to close for the time being?

**Comment by jugtej** [comment] 2016-10-01 20:01
sure

**Comment by ljacqu** [comment] 2016-10-01 20:02
If it happens again please drop a comment or reopen if you can and we'll just continue where we left off, lol

**Comment by jugtej** [comment] 2016-10-02 10:19
the issue came this
this is the console when people cant login http://pastebin.com/sx1t10vy i couldnt find any other plugin that wouldnt allow users to login as i dont have any spam plugin or any chat plugin other than essentials chat and simple prefix

**Comment by sgdc3** [comment] 2016-10-02 10:36
Duplicated

**Comment by sgdc3** [comment] 2016-10-02 10:37
You are using many old plugins, you should remove EssentialsXampp and switch to EssentialsX

Install that plugins:
https://ci.drtshock.net/job/essentialsx/lastSuccessfulBuild/artifact/Essentials/target/EssentialsX-2.0.1.jar
https://ci.drtshock.net/job/essentialsx/lastSuccessfulBuild/artifact/EssentialsChat/target/EssentialsXChat-2.0.1.jar
https://dev.bukkit.org/bukkit-plugins/simple-prefix/
http://ci.xephi.fr/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.2-SNAPSHOT-spigot.jar

**Comment by jugtej** [comment] 2016-10-02 18:20
i removed out all essentials and added essentials x i still have the issue im also on the latest build of simple prefix as well. is it possible to have it so authme has the highest priority so if there happens to be another plugin not allowing authme to run. it will stop?

**Comment by sgdc3** [comment] 2016-10-02 20:01
Commands doesn't have priorities in the bukkit api

**Comment by sgdc3** [comment] 2016-10-02 20:02
could you please post the output of the /version command and the content of your commands.yml file?

**Comment by sgdc3** [comment] 2016-10-04 20:08
@jugtej

**Comment by jugtej** [comment] 2016-10-06 16:04
sorry. my laptop had gone for repair.  when i do /version it says "  This server is running CraftBukkit version (git-PaperSpigot-"4c7641d") (MC:1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)"

**Comment by jugtej** [comment] 2016-10-06 16:10
# This is the commands configuration file for Bukkit.
# For documentation on how to make use of this file, check out the Bukkit Wiki at
# http://wiki.bukkit.org/Commands.yml
# 
# If you need help on this file, feel free to join us on irc or leave a message
# on the forums asking for advice.
# 
# IRC: #spigot @ irc.spi.gt
#    (If this means nothing to you, just go to http://www.spigotmc.org/pages/irc/ )
# Forums: http://www.spigotmc.org/
# Bug tracker: http://www.spigotmc.org/go/bugs

command-block-overrides: []
aliases:
  icanhasbukkit:
  - version $1-


This is it

**Comment by ljacqu** [comment] 2016-10-09 09:47
@jugtej I don't know if @sgdc3 has an idea what could be the cause. If not, I suggest to continue where we left off: https://github.com/Xephi/AuthMeReloaded/issues/961#issuecomment-250900309 The debug output from that JAR would be interesting to see

**Comment by ljacqu** [comment] 2016-10-13 19:39
Hi @jugtej any news from the debug log?

**Comment by sgdc3** [comment] 2016-10-13 21:37
I have no idea atm, maybe a plugin is cancelling the commandpreprocessevent

**Closed** 2016-10-22 09:07 UTC
Labels: no answer, not our fault
