### ISSUE TITLE
Random logouts, without any message

### ISSUE THREAD

**Issue by SmeXhy** [Xephi/AuthMeReloaded#419] opened 2016-01-07 09:42 UTC
I don't know why, but sometimes it logout me or my players, and I can't move, I can't anything, like when I didn't login. But it didn't write message: "You must login.." just I can't move, chat and doing nothing. I must type /login password or relog (so all are confused). Can you tell me why it's doing this?

**Comment by DNx5** [comment] 2016-01-07 22:49
What is your `/authme version` ?
Are session enabled?

**Comment by SmeXhy** [comment] 2016-01-07 23:55
My version is:
==========[ AuthMeReloaded ABOUT ]==========
> [00:52:40 INFO]: Version: AuthMeReloaded v5.2-SNAPSHOT (build: 662)

And yes, I have sessions enabled

**Comment by DNx5** [comment] 2016-01-08 00:32
probably it's caused by expired session.
AuthMe should send "Session expired." message on join, and maybe you couldn't see it because motd.

**Comment by DNx5** [comment] 2016-01-08 00:34
*TODO:*
* Ask player to login when session is expired.

**Comment by SmeXhy** [comment] 2016-01-08 01:14
But this problem is doing random while players are playing, for e.g. mining. They just suddenly can't move and do nothing (like when I am logouted, but with ANY messages of AuthMe). Command "/login pass" help, or relog too (then players can see sentence: "Use /login password to login!"). But I don't know why it's doing random while playing and without any message of AuthMe...

**Comment by sgdc3** [comment] 2016-01-08 06:49
Are you using any sort of reload command?

**Comment by SmeXhy** [comment] 2016-01-08 11:00
I am using plugman, but not on AuthMe (only sometimes, a long time ago)

**Comment by sgdc3** [comment] 2016-01-09 02:27
@DNx5 @ljacqu @Xephi we need to find out the cause of this issue :/

**Comment by Xephi** [comment] 2016-01-09 15:23
Yup, but i still can't reproduce it :/

**Comment by SmeXhy** [comment] 2016-01-09 15:26
But something is really doing that, and it's just RANDOM...

**Comment by Xephi** [comment] 2016-01-09 15:27
I will investigate, but i don't have any step to reproduce it, it will be hard :/

**Comment by SmeXhy** [comment] 2016-01-21 22:22
Well still it's just tottaly random. I think it can be some other plugin "fighting" with AuthMe? I don't know. I see no clues for this..

**Comment by sgdc3** [comment] 2016-01-21 23:07
Can you post your pl list please? (including bungee plugins)

**Comment by SmeXhy** [comment] 2016-01-21 23:31
There it is:
> [00:29:47 INFO]: Plugins (94): TitleAdvanced, OreBroadcast, LampControl, Vehicles, TintHealth, PlugMan, ParticlePack, RecipesGUI, FarmLimiter, SimpleReserve, AutomaticInventory, SkinsRestorer, PhantomAdmin, DeathMessages, EpicWorldGenerator, ParticleText, LightAPI, TopLite, AsyncWorldEditInjector, CoreProtect, dynmap, MoreTNTs, WorldEdit, AutoBot, ClearLag, WorldBorder, disablePvPFly, Votifier, ActionHealth, Yamler, Multiverse-Core, HeadBanner, ProtocolLib, LibsDisguises, Pl3xIcons, AsyncWorldEdit, GraviTree, PermissionsEx, FeatherBoard, Tab, ServerListPlus, GAListener, FakaHedaMinequery, HolographicDisplays, HideAndCustomPlugins, AnimatedNames, PlaceholderAPI, DeluxeJoin, CreativeControlByKubqoA, AuthMe, MobArena, Trading, DailyBonus, WorldGuard, NoFlyZone, RandomTeleport, MineCrates, Vote, TheUnderground, ProtectionLib, ServerSigns, CustomNoteBlock, Vault, GriefPrevention, ChestShop, BattlePets, GPGui, GPWelcome, FurnitureLib, GriefPrevention_Flags, JSONAPI, ShopGUIPlus, Essentials, MultiReplacements, Paintball, HeadDatabase, LiteBans, Fe, DeluxeChat, Citizens, Statistics, Signs, CraftBook, JDynmapGriefPrevention, DiceFurniture, CommandNPC, JSONAPIAddon, EssentialsSpawn, MessageAnnouncer, mcMMOAction, PortalGuns, ecoDrop, WeatherMan, WorldEditSelectionVisualizer

**Comment by sgdc3** [comment] 2016-01-22 06:49
looks like a very well assembled server

**Comment by sgdc3** [comment] 2016-01-22 06:55
I'll check if any of your plugins is using an improper way to hook into our api. ;)

**Comment by SmeXhy** [comment] 2016-01-22 11:43
Okey, thank you...

**Comment by DooKid** [comment] 2016-03-12 14:17
Hey, I've got the same problem and here are my plugins: WorldEdit, PermissionsEx, ClearLag, WorldBorder, ActionAnnouncer, HolographicDisplays, Vault, Random_Spawn, WorldGuard, HeavySpleef, Essentials, EssentialsChat, Jobs, ScoreboardStats, LWC, PreciousStones, PvPManager, EssentialsSpawn, AuthMe

Any finds?

**Comment by sgdc3** [comment] 2016-03-12 14:35
What's your authme buildNumber? (/authme version)

**Comment by DooKid** [comment] 2016-03-12 14:36
882.

**Comment by sgdc3** [comment] 2016-03-12 14:42
The server is under a bungeecord instance or directly accessible by players?

**Comment by DooKid** [comment] 2016-03-12 14:43
It is on spigot

**Comment by sgdc3** [comment] 2016-03-12 15:02
:/ Strange... @ljacqu @DNx5 @games647 Any ideas?

**Comment by DooKid** [comment] 2016-03-13 00:03
I've just deleted the authme config and now it looks like it is working properly. If it does that again i'll comment again. Thanks for the fast reply :)

**Comment by sgdc3** [comment] 2016-03-13 01:13
Do you have a backup of your broken config? I would like to compare it to the default one :/

**Comment by ljacqu** [comment] 2016-03-13 07:29
That would be very interesting indeed :)
@sgdc3 I don't have any idea :/
@DooKid and others experiencing this—right now it's really hard to diagnose the problem, so if it happens and again and it's not asking too much, kindly remember when it happens and share the authme.log with us :) If we know around which time it happened we can evaluate that log and maybe infer the cause.

**Comment by DooKid** [comment] 2016-03-13 09:47
Ok, I think i've got a backup http://pastebin.com/ANWHraue
I think the only thing I modify was the session thinghy, also I've upgraded to a better host, could the lag be a cause? Altho nobody said anything about lag before happening... also it happanes for one user at a time.

**Comment by DooKid** [comment] 2016-03-14 16:08
Hmm, the config did not fix it.. I still can't figure out what can interfere with authme..

**Comment by sgdc3** [comment] 2016-03-14 22:06
Maybe an outdated version of AuthMeBridge or AuthMeBungee(deprecated, please don't use it) ? :/

**Comment by DooKid** [comment] 2016-03-15 08:40
I've got spigot, not bungee.

**Comment by DooKid** [comment] 2016-03-17 14:13
I think it might be somehow lag related because since I upgraded my host it only happend one time in like 3-4 days. I have no ideea what could produce it, I'm going to let you know if I'll find more about this.

**Comment by sgdc3** [comment] 2016-03-31 23:41
@SmeXhy any news? ;)

**Comment by MarioAnak** [comment] 2016-04-03 12:30
I've the same issue... 
My authme version is v5.2-SNAPSHOT (build: 870)

Plugins on my Spigot server:
Plugins (57): MCItaliaRewards, ChunkLoader, Installer, SimpleHelpOp, Vault, NicePM, Backpacks, TreeAssist, Tablist, ArchonCrates, Announcer, ChestCommands, PerWorldPlugins, WhatIsIt, ProtocolLib, QuickShop, Citizens, DigitalClock, NoCheatPlus, ChatFilter, WorldEdit, LoggedFromAnotherLocationFix, SkinsModule, ChatControl, Skript, JoinCommands, MaxBans, TabCommandHider, AntiSpam, PermissionsEx, LogBlock, MyCommand, WorldGuard, AntiJoinBot, Commandspy, KeepItems, CommandBlockerUltimate, IP-Check, CoreProtect, ASkyBlock, iDisguise, VoidGenerator, AutoSaveWorld, Essentials, floAuction, ServerListPlus, Multiverse-Core, SilkSpawners, InfoBoardReborn, EssentialsChat, HolographicDisplays, EssentialsProtect, EssentialsSpawn, Multiverse-Inventories, TouchscreenHolograms, AuthMe, AuthMeBridge

On Bungee:
BungeeChat, BungeeCommandSpy, BungeeAuthMeBridge, BungeeHub, SkinsRestorer.

**Comment by sgdc3** [comment] 2016-04-03 22:35
What's your authmebridge version? Have you added AuthMe to the PerWorldPlugins ignore list?

**Comment by ReaperAngels** [comment] 2016-04-04 02:28
I've looked through the plugins of all the above people. Skinrestorer is the problem child. It causes a bit of lag, literally milliseconds, which could cause the problem. I use skinrestorer too, same issue. Hope this helps.

**Comment by sgdc3** [comment] 2016-04-04 05:55
Latest versions of skinrestorer are a bit unstable, but i didn't think it could cause such issues O_o

**Comment by MarioAnak** [comment] 2016-04-04 18:08
My AutMeBridge version is 1.6 (the lastest)... 
In PerWorldPlugins' config AuthMe is enabled over all the worlds

**Comment by DooKid** [comment] 2016-04-04 18:11
Skinrestorer isn't the problem, I had the problem before of it.

**Comment by ReaperAngels** [comment] 2016-04-04 18:28
OK, I was looking at what we all have in common. Skinrestorer and citizens were both on the list. I know Skinrestorer and citizens cause lag, where citizens cause the most. However, during the night I had the same problem on a server totally off the Internet, so both those two are eliminated, as they could not fetch skins. And I only have Skinrestorer on, not citizens. I know this makes it worse, not better. One thing though, just before I was logged out, I did //wand to paste builds and the do the regions. So could this be due to worldedit? To clarify, just did //wand, nothing else. Was about to tp to the spawn point where the build was going to be pasted in, could not move or do anything else until I logged in again.Using worldedit 6.1.1 snapshot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: DooKidSent: Monday 4 April 2016 20:11To: Xephi/AuthMeReloadedReply To: Xephi/AuthMeReloadedCc: ReaperAngelsSubject: Re: [Xephi/AuthMeReloaded] Random logouts, without any message (#419)Skinrestorer isn't the problem, I had the problem before of it.

—You are receiving this because you commented.Reply to this email directly or view it on GitHub

**Comment by sgdc3** [comment] 2016-04-04 19:01
I don't think it can be caused by lag issues, what's your database backend? @SmeXhy @DooKid @MarioAnak @ReaperAngels

**Comment by SmeXhy** [comment] 2016-04-04 19:16
I don't have server anymore, sorry, I can't help.

**Comment by ReaperAngels** [comment] 2016-04-04 19:20
Mysql, all the servers use the same database.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         From: Gabriele C.Sent: Monday 4 April 2016 21:01To: Xephi/AuthMeReloadedReply To: Xephi/AuthMeReloadedCc: ReaperAngelsSubject: Re: [Xephi/AuthMeReloaded] Random logouts, without any message (#419)I don't think it can be caused by lag issues, what's your database backend? @SmeXhy @DooKid @MarioAnak @ReaperAngels 

—You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub

**Comment by ReaperAngels** [comment] 2016-04-04 19:20
Mysql, all the servers use the same database. However, I'm only running one server at a time, as I'm still busy building it. Spigot 1.9.2, no bungee for now                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Gabriele C.Sent: Monday 4 April 2016 21:01To: Xephi/AuthMeReloadedReply To: Xephi/AuthMeReloadedCc: ReaperAngelsSubject: Re: [Xephi/AuthMeReloaded] Random logouts, without any message (#419)I don't think it can be caused by lag issues, what's your database backend? @SmeXhy @DooKid @MarioAnak @ReaperAngels 

—You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub

**Comment by DooKid** [comment] 2016-04-05 12:25
I've got the normal data base, standard.

**Comment by Mabus13** [comment] 2016-05-02 14:52
How doing with fix that problem?

**Comment by games647** [comment] 2016-05-03 09:50
I think it could be this: 
https://github.com/Xephi/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/datasource/CacheDataSource.java#L44

But I really don't know.
Maybe we should add some debug code, when it tries to refetch the profile.

**Comment by ReaperAngels** [comment] 2016-05-06 13:08
Hi guys,

To be honest, the server has been up for a month, without any problems with
that. The only real "problem" is that occasionally you have to relog when
you change servers. But other than that is has been smooth-sailing.

I do need some help with another matter. How to disable logins beginning
with "town" and "nation".

Thanks for the help so far!

Grimreaper

**Comment by astr1al** [comment] 2016-05-10 01:47
Still happens on build #997, I have many plugins too but seeing as DooKid and I share a few plugins and his list is relatively small, here are the plugins him and I share

 WorldEdit, WorldBorder, HolographicDisplays, Vault, WorldGuard, HeavySpleef, Jobs, PreciousStones. I wish I could offer more info, the only thing I notice is there is a few seconds of client side lag before getting teleported back to spawn and asked to login. The server runs on a 60/60 connection and the cpu isn't overloaded at the time.

**Comment by sgdc3** [comment] 2016-05-10 05:55
@ljacqu @games647 We really need to focus on this.

**Comment by Xephi** [comment] 2016-05-15 15:54
Can you please make some try with the latest devbuild please ?

**Comment by sgdc3** [comment] 2016-05-16 14:32
@SmeXhy

**Comment by ReaperAngels** [comment] 2016-05-17 23:08
OK. Found out some info the hard way. java 1.8.0_77 has a mysql (amongst others) bug, where it drops the database connection. I've updated to 1.8.0_91. I'm now on bungee, with 3 servers running on spigot 1.9.2 latest builds. I have not had the logout problem again. Not using authmebridge, just authme on a shared database. The database problem is still there on the new java. Better, but still not 100% sorted. I check with tcpdump on port 3306 and piping to a file. So the date/time stamps are all there. Interestingly enough on one such test, with players logging on, there was no traffic. None. So nothing was using mysql? Not on my config. most plugins are linked to a database. So I would suggest looking at java as the culprit. And I haven't updated to the latest authme yet. Still same build. Hope it helps

**Comment by Mabus13** [comment] 2016-05-22 00:02
I just try that build #1​03​0 21.05.2016 11:55

Problem random logout exist. =(((((((( Need play few minutes not more half hout and my oped char logouted. Not need be afk you can do anything, but that logot end all your doing. =((((((((

Please guys fix it!!!

p.s. also when i logout not always saved coords where i exit. Like 70%

**Comment by Dibro89** [comment] 2016-05-25 19:24
#1056 still not fixed.
Here's a part of my authme.log:
[05-25 22:04:55]: Debug: ADDED PLAYER TO CACHE dibro
[05-25 22:07:16]: Debug: REMOVE PLAYER dibro
[05-25 22:07:19]: Dibro logged in!
[05-25 22:07:19]: Debug: ADDED PLAYER TO CACHE dibro
[05-25 22:07:19]: Debug: REFRESH dibro

**Comment by sgdc3** [comment] 2016-05-25 19:40
@Xephi Any idea?

**Comment by games647** [comment] 2016-06-01 14:34
Thank you for the log. @Dibro89 

Looks like the player is explicitly removed from the local data set.

**Comment by games647** [comment] 2016-06-03 12:36
Users who still have this issue, should try a build above # 1078 and activate debug logging in the spigot configuration. It would print a stacktrace of every cache modification, so it could be quite spamy.

**Comment by Dibro89** [comment] 2016-06-16 06:35
I didn't have this issue for a while but some of my players do. You should not close it atm

**Comment by sgdc3** [comment] 2016-06-16 07:52
It have been closed by github itself, sorry

**Comment by games647** [comment] 2016-06-16 08:41
@Dibro89 Then could you please upgrade your build give us the debug data we need.

**Comment by Dibro89** [comment] 2016-06-16 10:30
@games647 Sure.

**Comment by molor** [comment] 2016-06-27 17:50
okay, Here are m logs from authme.log file:

[06-27 20:04:33]: Debug: AuthMe-CacheLoader:REFRESH /me/
[06-27 20:04:33]: /me/ logged in!
[06-27 20:04:33]: Debug: Craft Scheduler Thread - 176:ADDED PLAYER TO CACHE /me/
[06-27 20:35:43]: Debug: Craft Scheduler Thread - 192:REMOVE PLAYER /me/
// After this point I have to enter /login again to continue playing.
// All the time starting 20:04:33 I was on the server..
[06-27 20:43:39]: Debug: AuthMe-CacheLoader:REFRESH /me/
[06-27 20:43:39]: /me/ logged in!
[06-27 20:43:39]: Debug: Craft Scheduler Thread - 194:ADDED PLAYER TO CACHE /me/

**Comment by ljacqu** [comment] 2016-06-27 19:04
> [06-27 20:35:43]: Debug: Craft Scheduler Thread - 192:REMOVE PLAYER /me/

Would you mind sharing a few lines above and below this? Essentially the question is what is triggering this. You don't have any stacktraces in the logs, do you?

**Comment by molor** [comment] 2016-06-28 06:36
This is part of this log without any deletions:
```
[06-27 19:34:10]: Debug: AuthMe-CacheLoader:REFRESH kaptoxa_play
[06-27 19:34:10]: KAPTOXA_Play logged in!
[06-27 19:34:10]: Debug: Craft Scheduler Thread - 163:ADDED PLAYER TO CACHE kaptoxa_play
[06-27 19:35:05]: Debug: AuthMe-CacheLoader:REFRESH kaptoxa_play
[06-27 19:53:04]: Debug: Craft Scheduler Thread - 169:REMOVE PLAYER kaptoxa_play
[06-27 19:53:04]: Debug: AuthMe-CacheLoader:REFRESH kaptoxa_play
[06-27 19:53:04]: KAPTOXA_Play logged in!
[06-27 19:53:04]: Debug: Craft Scheduler Thread - 173:ADDED PLAYER TO CACHE kaptoxa_play
[06-27 19:55:51]: Debug: AuthMe-CacheLoader:REFRESH kaptoxa_play
[06-27 19:56:25]: Debug: Craft Scheduler Thread - 173:REMOVE PLAYER kaptoxa_play
[06-27 19:56:26]: Debug: AuthMe-CacheLoader:REFRESH kaptoxa_play
[06-27 19:56:26]: KAPTOXA_Play logged in!
[06-27 19:56:26]: Debug: Craft Scheduler Thread - 173:ADDED PLAYER TO CACHE kaptoxa_play
[06-27 20:03:31]: Debug: Craft Scheduler Thread - 176:REMOVE PLAYER molorzz
[06-27 20:04:33]: Debug: AuthMe-CacheLoader:REFRESH molorzz
[06-27 20:04:33]: molorZz logged in!
[06-27 20:04:33]: Debug: Craft Scheduler Thread - 176:ADDED PLAYER TO CACHE molorzz
[06-27 20:11:02]: Debug: AuthMe-CacheLoader:REFRESH kaptoxa_play
[06-27 20:35:43]: Debug: Craft Scheduler Thread - 192:REMOVE PLAYER molorzz
[06-27 20:42:35]: Debug: Craft Scheduler Thread - 193:REMOVE PLAYER kaptoxa_play
[06-27 20:43:39]: Debug: AuthMe-CacheLoader:REFRESH molorzz
[06-27 20:43:39]: molorZz logged in!
[06-27 20:43:39]: Debug: Craft Scheduler Thread - 194:ADDED PLAYER TO CACHE molorzz
[06-27 20:54:49]: Debug: AuthMe-CacheLoader:REFRESH heretic926
[06-27 20:54:49]: Heretic926 logged in!
[06-27 20:54:49]: Debug: Craft Scheduler Thread - 196:ADDED PLAYER TO CACHE heretic926
[06-27 20:58:54]: Debug: AuthMe-CacheLoader:REFRESH heretic926
[06-27 20:58:58]: Debug: Craft Scheduler Thread - 202:REMOVE PLAYER heretic926
[06-27 20:58:58]: Debug: AuthMe-CacheLoader:REFRESH heretic926
[06-27 20:58:58]: Heretic926 logged in!
[06-27 20:58:58]: Debug: Craft Scheduler Thread - 202:ADDED PLAYER TO CACHE heretic926
```

> You don't have any stacktraces in the logs, do you?

No..

**Comment by games647** [comment] 2016-06-28 09:13
@molor Could you enable debug logging in your debug configuration and then give us the server log (not authme log) when it happens again.

**Comment by molor** [comment] 2016-06-28 09:19
@games647, ok, waiting..

**Comment by molor** [comment] 2016-06-28 12:14
```
[15:10:55] [Craft Scheduler Thread - 284/TRACE]: [AuthMe] REMOVE PLAYER mr_dimanchec3 Craft Scheduler Thread - 284
java.lang.Exception
	at fr.xephi.authme.ConsoleLogger.debug(ConsoleLogger.java:75) [AuthMe-5.2-BETA3-spigot.jar:?]
	at fr.xephi.authme.cache.auth.PlayerCache.removePlayer(PlayerCache.java:57) [AuthMe-5.2-BETA3-spigot.jar:?]
	at fr.xephi.authme.process.quit.AsynchronousQuit.postLogout(AsynchronousQuit.java:118) [AuthMe-5.2-BETA3-spigot.jar:?]
	at fr.xephi.authme.process.quit.AsynchronousQuit.access$000(AsynchronousQuit.java:25) [AuthMe-5.2-BETA3-spigot.jar:?]
	at fr.xephi.authme.process.quit.AsynchronousQuit$1.run(AsynchronousQuit.java:92) [AuthMe-5.2-BETA3-spigot.jar:?]
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_66]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
[15:12:10] [Server thread/INFO]: mr_dimanchec3 issued server command: /login qwerty
[15:12:10] [AuthMe-CacheLoader/TRACE]: [AuthMe] REFRESH mr_dimanchec3 AuthMe-CacheLoader
java.lang.Exception
	at fr.xephi.authme.ConsoleLogger.debug(ConsoleLogger.java:75) [AuthMe-5.2-BETA3-spigot.jar:?]
	at fr.xephi.authme.datasource.CacheDataSource$1$1.call(CacheDataSource.java:57) [AuthMe-5.2-BETA3-spigot.jar:?]
	at fr.xephi.authme.datasource.CacheDataSource$1$1.call(CacheDataSource.java:54) [AuthMe-5.2-BETA3-spigot.jar:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_66]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
[15:12:10] [Craft Scheduler Thread - 285/INFO]: [AuthMe] mr_dimanchec3 logged in!
[15:12:10] [Craft Scheduler Thread - 285/TRACE]: [AuthMe] ADDED PLAYER TO CACHE mr_dimanchec3 Craft Scheduler Thread - 285
java.lang.Exception
	at fr.xephi.authme.ConsoleLogger.debug(ConsoleLogger.java:75) [AuthMe-5.2-BETA3-spigot.jar:?]
	at fr.xephi.authme.cache.auth.PlayerCache.addPlayer(PlayerCache.java:37) [AuthMe-5.2-BETA3-spigot.jar:?]
	at fr.xephi.authme.process.login.AsynchronousLogin.login(AsynchronousLogin.java:193) [AuthMe-5.2-BETA3-spigot.jar:?]
	at fr.xephi.authme.process.Management$1.run(Management.java:50) [AuthMe-5.2-BETA3-spigot.jar:?]
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot-1.9.4.jar:git-Spigot-4af49dc-4e19de1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_66]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
```

**Comment by games647** [comment] 2016-06-28 12:16
@molor Exactly. Could you point out there the random logout happened.

**Comment by molor** [comment] 2016-06-28 12:18
@games647, see edited comment.

**Comment by games647** [comment] 2016-06-28 12:25
@AuthMe-Team/authme-developers Do you have any clues about this?`

    ```at fr.xephi.authme.process.quit.AsynchronousQuit$1.run(AsynchronousQuit.java:92)```
This task is called although the player doesn't quiet the server.

**Comment by sgdc3** [comment] 2016-06-28 12:26
Let's find out

**Comment by sgdc3** [comment] 2016-06-28 12:39
The perform quit is called only by the kick and quit event, the only cause can be another plugin...

**Comment by sgdc3** [comment] 2016-06-28 12:40
@molor could you post your plugin list?

**Comment by molor** [comment] 2016-06-28 12:47
AuthMe, AutoSaveWorld, PermissionsEx, ProtocolLib, SkinsRestorer, WorldEdit, WorldGuard.

**Comment by sgdc3** [comment] 2016-06-28 12:50
WTF IS THAT
```Java
                BukkitTask task = plugin.getServer().getScheduler().runTaskLaterAsynchronously(plugin, new Runnable() {

                    @Override
                    public void run() {
                        postLogout(name);
                    }

                }, Settings.getSessionTimeout * TICKS_PER_MINUTE);
```

**Comment by sgdc3** [comment] 2016-06-28 12:51
runTaskLaterAsynchronously Settings.getSessionTimeout * TICKS_PER_MINUTE

**Comment by sgdc3** [comment] 2016-06-28 12:51
....

**Comment by sgdc3** [comment] 2016-06-28 12:52
@games647 @DNx5 @ljacqu @Gnat008 @Xephi

**Comment by molor** [comment] 2016-06-28 12:56
Really?!

**Comment by sgdc3** [comment] 2016-06-28 12:58
Now i want to know who did this xD

**Comment by Dibro89** [comment] 2016-06-28 13:00
But why is it random?

**Comment by sgdc3** [comment] 2016-06-28 13:01
wait, no this is an issue tih latest build (@Gnat008 's fault :P)

**Comment by sgdc3** [comment] 2016-06-28 13:11
TEMP FIX: disable sessions

**Comment by sgdc3** [comment] 2016-06-28 13:12
@SmeXhy @molor @Dibro89

**Comment by molor** [comment] 2016-06-28 13:34
I have to turn off sessions and see if it can happen again without them?
If I understand correctly, wait..

**Comment by sgdc3** [comment] 2016-06-28 13:35
Correction: this issue happens when sesion IS NOT enabled

**Comment by sgdc3** [comment] 2016-06-28 13:36
can you confirm this @molor ?

**Comment by molor** [comment] 2016-06-28 13:38
> this issue happens when sesion IS NOT enabled

No, my config is:
```
sessions: 
   enabled: true
   timeout: 30
   sessionExpireOnIpChange: true
```

**Comment by molor** [comment] 2016-07-26 08:35
Since this bug I no longer met, we can assume that it is fixed.

**Comment by ljacqu** [comment] 2016-07-26 08:49
Thank you!

**Closed by ljacqu** 2016-07-26 08:49 UTC
Labels: bug, critical
