### ISSUE TITLE
[AuthMe-5.2-SNAPSHOT-legacy.1457] Some players can't move after login.

### ISSUE THREAD

**Issue by Arano-kai** [Xephi/AuthMeReloaded#1006] opened 2016-11-13 18:35 UTC
### What behaviour is observed:
Under some conditions players can't move after login.

### What behaviour is expected:
Free movement is one of the basic human rights =)

### Steps/models to reproduce:
1. Join unregistered user
2. Try to move/jump, but don't register and get kicked/disconnect
3. Repeat, but now register
4. ??????
5. OH, WHERE IS MY LEGS??! (but I can do jump-move however...)

### Plugin list:
Don't matter...

### Environment description:
Thermos-1.7.10-1614.58a

### AuthMe build number:
AuthMeReloaded v5.2-SNAPSHOT (build: 1457 legasy)
Older snaps also affected.

### Configuration:
```
  allowMovement: false
  removeSpeed: true
```
[Full config.yml](http://pastebin.com/6scHp4Bs)

### The reasons for the phenomenon:
After disconnect AuthMe creates AuthMe/playerdata/{UUID}/data.json, with content:
```
~~~~~~~~~
  "walk-speed": 1.0E-4,
  "fly-speed": 1.0E-4 
```
### Workaround:

- For affected users edit those two values to `0.2` and `0.1` respectively
- In config set `allowMovement: true` and `removeSpeed: false`

**Comment by Platinteufel** [comment] 2016-11-14 01:04
#890 
Seems like this is still a legacy issue. I can't reproduce it on my Spigot 1.10.2 server at all.

**Comment by sgdc3** [comment] 2016-11-14 17:05
ok i'll create a workaround

**Comment by sgdc3** [comment] 2016-11-14 18:08
@Arano-kai Should be fixed, could you test it please? ;)

**Comment by Arano-kai** [comment] 2016-11-17 11:38
Tested on 1460 (legacy) and there is no problem anymore. Thank You =)

**Comment by sgdc3** [comment] 2016-11-17 12:19
Thank you ;)

**Closed** 2016-11-17 12:19 UTC
